# Assignment: Classes, Objects & Inheritance in Python

> **Topics Covered:** Classes, Objects, Attributes, Methods, `__init__`, `self`, Inheritance, `super()`, Method Overriding 
> **Bonus Section:** Git & GitHub basics 
> **Difficulty:** Beginner to Intermediate 
> **Instructions:** 
> - Write your code in the cells provided below each question 
> - Run each cell to verify your output 
> - Some questions have **expected output** — match it exactly 
> - Questions marked are slightly harder — give them a shot!

---

## Section 1: Warm-Up — Everything is an Object 

These are quick questions to reinforce what you saw in class.

### Q1. Type Detective

Use `type()` to find the class/type of each value below. Print each result.

```
5
"hello"
3.14
[1, 2, 3]
True
{"name": "Rahul"}
(1, 2)
None
```

**What pattern do you notice in the output?**

In [1]:
# Your code here
print(type(5))
print(type("hello"))
print(type(3.14))
print(type([1,2,3]))
print(type(True))
print(type({"name":"Rahul"}))
print(type((1,2)))
print(type(None))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>
<class 'bool'>
<class 'dict'>
<class 'tuple'>
<class 'NoneType'>


### Q2. X-Ray Vision

Use `dir()` on a string `"python"` and answer:

1. How many methods does a string object have? (use `len()` on the `dir()` output)
2. Pick any **3 methods** you haven't used before, call them on `"python"`, and print the results
3. Use `help()` on one of those methods to read what it does

In [2]:
# Your code here
name = "python"
print(dir(name))
# 1. Total number of methods
print(len(dir(name))) #81
#81 methods are there on string
# 2. Try 3 new methods
print(name.isidentifier())
print(name.removeprefix("py"))
print(name.removesuffix("on"))
# 3. Use help() on one method
print(help(name.lstrip))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
81
True
thon
pyth
H

### Q3. The Operator Secret

Without running the code first, **predict the output** of each line. Then run it to verify.

```python
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))
```

**In your own words:** Why does `+` behave differently for integers, strings, and lists?

In [3]:
# First write your predictions as comments, then run to verify

# (10).__add__(5) → I predict: 15
# "hello ".__add__("world") → I predict: helloworld
# [1,2].__add__([3,4]) → I predict: [1,2,3,4]
# (10).__mul__(3) → I predict: 30
# "ha".__mul__(3) → I predict: hahaha

# Now run them:
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))


15
hello world
[1, 2, 3, 4]
30
hahaha


**Your explanation (why does `+` behave differently?):**

*Write here...*

--- I think + is an example of polymorphism same function or method but performs differently on different objects i.e strings and integers 

## Section 2: Building Your First Classes 

### Q4. Create a `Book` class

Create a class called `Book` with:
- **Attributes:** `title`, `author`, `pages`, `price`
- **Method:** `get_summary()` → returns a string like: `"Atomic Habits by James Clear — 320 pages — ₹500"`

Then:
1. Create 3 book objects
2. Print the summary of each book
3. Print the `type()` of any one book object

**Expected output format:**
```
Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>
```

In [4]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.pages=pages
        self.author=author
        self.price=price
    def get_summary(self):
        print(f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}")

b1=Book("Atomic Habits","James Clear",320,500)
b2=Book("Deep Work","Cal Newport",296,450)
b3=Book("Python Crash Course","Eric Matthes",544,600)
b1.get_summary()
b2.get_summary()
b3.get_summary()
print(type(b1))


Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>


### Q5. Add Behavior — `apply_discount()`

Add a method `apply_discount(percent)` to your `Book` class that:
- Reduces the price by the given percentage
- Prints: `"Discount applied! New price of 'Atomic Habits': ₹400"`

Also add a method `is_long_read()` that:
- Returns `True` if pages > 400, else `False`

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True
```

In [5]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.pages=pages
        self.author=author
        self.price=price
    def get_summary(self):
        print(f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}")
    def apply_discount(self,percent):
        self.discount=self.price-(self.price*(percent/100))
        print(f"Discount Applied! New price of '{self.title}': ₹{self.discount}")
    def is_long_read(self):
        if(self.pages>400):
            return True
        else:
            return False
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True

Discount Applied! New price of 'Atomic Habits': ₹400.0
False
True


### Q6. The `__str__` Magic Method

Right now, if you `print(book_object)`, you get something ugly like `<__main__.Book object at 0x...>`.

Fix this by adding a `__str__` method to your Book class so that `print(book)` directly shows the summary.

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b) # Should print: Atomic Habits by James Clear — 320 pages — ₹500
```

**Hint:** Remember how `str` class has `__add__` for `+`? Similarly `__str__` controls what `print()` shows.

In [6]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.pages=pages
        self.author=author
        self.price=price
    def __str__(self):
        return f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}"
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b)

Atomic Habits by James Clear — 320 pages — ₹500


### Q7. `BankAccount` Class

Create a `BankAccount` class with:
- **Attributes:** `owner`, `balance` (default 0)
- **Methods:**
 - `deposit(amount)` → adds to balance, prints confirmation
 - `withdraw(amount)` → subtracts from balance BUT prints `"Insufficient funds!"` if amount > balance
 - `get_balance()` → returns a formatted string: `"Rahul's balance: ₹5000"`

```python
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000
```

In [7]:
# Your code here
class BankAccount:
    def __init__(self,owner,balance=0):
        self.owner=owner
        self.balance=balance
    def deposit(self,amount):
        self.balance+=amount
        print(f"Deposited ₹{amount}. New balance: ₹{self.balance}")
    def withdraw(self,amount):
        if(amount>self.balance):
            print(f"Insufficient funds! Current balance: ₹{self.balance}")
        else:
            self.balance-=amount
            print(f"Withdrew ₹{amount}. New balance: ₹{self.balance}")
    def get_balance(self):
        return self.balance
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) 
acc.withdraw(3000) 
acc.withdraw(20000) 
print(f"{acc.owner}'s balance: ₹{acc.get_balance()}")

Deposited ₹5000. New balance: ₹15000
Withdrew ₹3000. New balance: ₹12000
Insufficient funds! Current balance: ₹12000
Rahul's balance: ₹12000


### Q8. Parameter vs Attribute vs Argument

Look at this code and answer the questions below:

```python
class Car:
 def __init__(self, brand, speed):
 self.brand = brand
 self.top_speed = speed
 self.is_running = False
 
 def start(self):
 self.is_running = True

my_car = Car("Toyota", 180)
```

**Answer these in the markdown cell below:**
1. What are the **parameters** of `__init__`?
2. What are the **arguments** passed when creating `my_car`?
3. What are the **attributes** of a `Car` object?
4. What is the **method** in this class?
5. Why is `speed` a parameter but `top_speed` is an attribute? Are they the same thing?

**Your answers:**

1. Parameters: self,brand,speed
2. Arguments: Toyota,180
3. Attributes: brand,top_speed,is_running
4. Method: start
5. Explanation: top_speed is an attribute because its like a property or a state  of object Car and speed is a parameter which is passed to the method. No, they are not same.


---

## Section 3: Inheritance 

### Q9. `Animal` → `Dog` → `Cat`

Create a base class `Animal` with:
- **Attributes:** `name`, `sound`
- **Method:** `speak()` → returns `"<name> says <sound>!"`

Then create two child classes:
- `Dog(Animal)` — automatically sets sound to `"Woof"`, adds a method `fetch()` that returns `"<name> fetches the ball!"`
- `Cat(Animal)` — automatically sets sound to `"Meow"`, adds a method `purr()` that returns `"<name> purrs softly..."`

```python
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
```

In [8]:
# Your code here
class Animal:
    def __init__(self,name,sound):
        self.name=name
        self.sound=sound
    def speak(self):
        return f"{self.name} says {self.sound}!"
class Dog(Animal):
    def __init__(self,name):
        super().__init__(name,"Woof")
    def fetch(self):
        return f"{self.name} fetches the ball!"
class Cat(Animal):
    def __init__(self,name):
        super().__init__(name,"Meow")
    def purr(self):
        return f"{self.name} purrs softly..."

d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
        
    
        

Bruno says Woof!
Bruno fetches the ball!
Whiskers says Meow!
Whiskers purrs softly...


### Q10. Employee Management — Full Hierarchy

Build the Employee system from class:

**Base class `Employee`:**
- Attributes: `name`, `emp_id`, `salary`, `department`
- Methods:
 - `get_details()` → `"[E001] Rahul | Engineering | ₹50000"`
 - `give_raise(amount)` → increases salary (only if amount > 0)
 - `calculate_bonus()` → returns 10% of salary

**Child class `Manager(Employee)`:**
- Extra attribute: `team_size`
- Override `calculate_bonus()` → returns 20% of salary
- New method: `approve_leave(emp_name)` → `"Priya approved leave for Rahul"`

**Child class `Intern(Employee)`:**
- Extra attribute: `mentor`
- Override `calculate_bonus()` → returns 5% of salary
- New method: `get_mentor()` → `"Amit's mentor is Priya"`

Then create a list of 5 employees (mix of Employee, Manager, Intern) and loop through them to print details and bonus for each.

**Expected output format:**
```
[E001] Rahul | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 → Bonus: ₹1000.0
...
```

In [9]:
# Your code here
class Employee:
    def __init__(self,name,emp_id,salary,department):
        self.name=name
        self.emp_id=emp_id
        self.salary=salary
        self.department=department
    def get_details(self):
        print(f"[{self.emp_id}] {self.name} | {self.department} | {self.salary} → ",end="")
    def give_raise(self,amount):
        if(amount>0):
            self.salary+=amount
    def calculate_bonus(self):
        return 0.1*self.salary
class Manager(Employee):
    def __init__(self,name,emp_id,salary,department,team_size):
        super().__init__(name,emp_id,salary,department)
        self.team_size=team_size
    def calculate_bonus(self):
        return 0.2*self.salary
    def approve_leave(self,emp_name):
        print(f"{self.name} approved leave for {emp_name}")
class Intern(Employee):
    def __init__(self,name,emp_id,salary,department,mentor):
        super().__init__(name,emp_id,salary,department)
        self.mentor=mentor
    def calculate_bonus(self):
        return 0.05*self.salary
    def get_mentor(self):
        print(f"{self.name} mentor is {self.mentor}")
e1=Employee("Rahul","E001",50000,"Engineering")
e2=Manager("Priya","M001",90000,"Engineering",5)
e3=Intern("Amit","I001",20000,"Engineering","Priya")
e4=Intern("Pooja","I002",25000,"Engineering","Rahul")
e5=Employee("Bob","E002",60000,"Engineering")
e_list=[e1,e2,e3,e4,e5]
for emp in e_list:
    emp.get_details()
    print(f"Bonus : ₹{emp.calculate_bonus()}")


        
        
        
        


[E001] Rahul | Engineering | 50000 → Bonus : ₹5000.0
[M001] Priya | Engineering | 90000 → Bonus : ₹18000.0
[I001] Amit | Engineering | 20000 → Bonus : ₹1000.0
[I002] Pooja | Engineering | 25000 → Bonus : ₹1250.0
[E002] Bob | Engineering | 60000 → Bonus : ₹6000.0


### Q11. `isinstance()` Check

Using the employees list from Q10, write a loop that:
1. Prints `"Manager alert!"` for any Manager objects
2. Prints the mentor name for any Intern objects 
3. Just prints details for regular Employees

**Hint:** Use `isinstance(obj, ClassName)` to check the type.

In [10]:
# Your code here
class Employee:
    def __init__(self,name,emp_id,salary,department):
        self.name=name
        self.emp_id=emp_id
        self.salary=salary
        self.department=department
    def get_details(self):
        print(f"[{self.emp_id}] {self.name} | {self.department} | {self.salary}")
    def give_raise(self,amount):
        if(amount>0):
            self.salary+=amount
    def calculate_bonus(self):
        return 0.1*self.salary
class Manager(Employee):
    def __init__(self,name,emp_id,salary,department,team_size):
        super().__init__(name,emp_id,salary,department)
        self.team_size=team_size
    def calculate_bonus(self):
        return 0.2*self.salary
    def approve_leave(self,emp_name):
        print(f"{self.name} approved leave for {emp_name}")
class Intern(Employee):
    def __init__(self,name,emp_id,salary,department,mentor):
        super().__init__(name,emp_id,salary,department)
        self.mentor=mentor
    def calculate_bonus(self):
        return 0.05*self.salary
    def get_mentor(self):
        print(f"{self.name} mentor is {self.mentor}")
e1=Employee("Rahul","E001",50000,"Engineering")
e2=Manager("Priya","M001",90000,"Engineering",5)
e3=Intern("Amit","I001",20000,"Engineering","Priya")
e4=Intern("Pooja","I002",25000,"Engineering","Rahul")
e5=Employee("Bob","E002",60000,"Engineering")
e_list=[e1,e2,e3,e4,e5]
for emp in e_list:
    if isinstance(emp, Manager):
        print("Manager Alert!")

    elif isinstance(emp, Intern):
        print(emp.mentor)

    elif isinstance(emp, Employee):
        emp.get_details()
        

[E001] Rahul | Engineering | 50000
Manager Alert!
Priya
Rahul
[E002] Bob | Engineering | 60000


### Q12. The `super()` Deep Dive

Look at this code:

```python
class Vehicle:
 def __init__(self, brand, year):
 self.brand = brand
 self.year = year
 print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
 super().__init__(brand, year)
 self.battery_kwh = battery_kwh
 print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
```

**Answer these:**
1. What will be printed when `tesla` is created? (predict first, then run)
2. What does `super().__init__(brand, year)` actually do?
3. What would happen if you remove the `super()` line? Try it — what attributes does `tesla` have now?
4. Why do we pass `brand` and `year` to `super().__init__()` but NOT `battery_kwh`?

In [11]:
# Test your predictions here
 
class Vehicle:
   def __init__(self, brand, year):
      self.brand = brand
      self.year = year
      print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
   def __init__(self, brand, year, battery_kwh):
      super().__init__(brand, year)
      self.battery_kwh = battery_kwh
      print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)


Vehicle __init__ called for Tesla
ElectricCar __init__ called for Tesla


**Your answers:**

1. Printed output: Vehicle __init__ called for Tesla, ElectricCar __init__ called for Tesla(because first parent constructor is called then child constructor is executed)
2. What super() does:  super().__init_-(brand,year) actually calls the parent class constructor and initializes the object with passed values
3. Without super(): if super() line is removed the ElectricCar does not initialize with brand,year and has only one attribute battery_kwh 
4. Why not pass battery_kwh: we do not pass brand and year to super().__init__() the class  ElectricCar is not intialised with these attributes but not with battery_kwh because this attribute belongs to ElectricCar objects and it is unique for every brand object.

---

## Section 4: Challenge Problems

### Q13. Library System

Build a mini library:

**`Book` class:**
- Attributes: `title`, `author`, `is_available` (default True)

**`Library` class:**
- Attribute: `books` (an empty list to start)
- Methods:
 - `add_book(book)` → adds a Book object to the library
 - `show_available()` → prints only books where `is_available` is True
 - `lend_book(title)` → finds the book by title, sets `is_available = False`, prints confirmation. If not found or not available, print an error.
 - `return_book(title)` → finds the book, sets `is_available = True`
 - `search(keyword)` → returns all books where keyword is in the title OR author name (case-insensitive)

```python
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course
```

In [12]:
# Your code here
class Book:
    def __init__(self,title,author,is_available=True):
        self.title=title
        self.author=author
        self.is_available=is_available
class Library:
    def __init__(self):
        self.books=[]
    def add_book(self,book):
        self.books.append(book)
    def show_available(self):
        print("Available Books:")
        for book in self.books:
            if(book.is_available):
                print(f"{book.title} by {book.author}")
                found=True
        if not found:
                print("No books available")
                
    def lend_book(self,title ):
        for book in self.books:
            if book.title.lower()==title.lower():
                 if book.is_available:
                      book.is_available=False
                      print(f"You borrowed {book.title}")
                      return
                 else:
                     print(f"{book.title} is already borrowed")
                     return
        print("Book not found!")
    def return_book(self,title):
        for book in self.books:
            if book.title.lower()==title.lower():
                if not book.is_available:
                    book.is_available=True
                    print(f"You returned {book.title}")
                    return
                else:
                    print(f"{book.title} is not borrowed")
                    return
        print("Book not found!")
    def search(self,keyword):
        keyword=keyword.lower()
        for book in self.books:
            if keyword in book.title.lower() or keyword in book.author.lower():
                print(book.title)
lib = Library()
b1=Book("Atomic Habits", "James Clear")
b2=Book("Deep Work", "Cal Newport")
b3=Book("Python Crash Course", "Eric Matthes")
lib.add_book(b1)
lib.add_book(b2)
lib.add_book(b3)
lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") #
#lib.add_book(Book("Atomic Habits", "James Clear"))
#lib.add_book(Book("Deep Work", "Cal Newport"))
#lib.add_book(Book("Python Crash Course", "Eric Matthes"))
        
                
        
        
    

Available Books:
Atomic Habits by James Clear
Deep Work by Cal Newport
Python Crash Course by Eric Matthes
You borrowed Deep Work
Available Books:
Atomic Habits by James Clear
Python Crash Course by Eric Matthes
Deep Work is already borrowed
You returned Deep Work
Python Crash Course


### Q14. School Report Card System

Build a system with:

**`Student` class:**
- Attributes: `name`, `roll_no`, `marks` (a dictionary like `{"math": 85, "science": 90, "english": 78}`)
- Methods:
 - `average()` → returns the average of all marks
 - `highest_subject()` → returns the subject with the highest mark
 - `pass_or_fail()` → returns `"Pass"` if average >= 40, else `"Fail"`
 - `__str__()` → nice formatted string

**`Topper(Student)` — inherits from Student:**
- Override `__str__()` to add a at the end
- New method: `motivational_quote()` → returns `"<name> says: Hard work pays off!"`

Create 3 students, find who has the highest average (the topper), and print everyone's report card.

**Expected output format:**
```
--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102 
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
Priya says: Hard work pays off!
```

In [13]:
# Your code here
class student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

    def average(self):
        total = 0
        for mark in self.marks.values():
            total += mark
        return total / len(self.marks)

    def highest_subject(self):
        high_mark = 0
        high_sub = ""
        for sub, mark in self.marks.items():
            if mark > high_mark:
                high_mark = mark
                high_sub = sub
        return high_sub

    def pass_or_fail(self):
        return "Pass" if self.average() >= 40 else "Fail"

    def __str__(self):
        return (f"--- Report Card ---\n"
                f"Name: {self.name} | Roll No: {self.roll_no}\n"
                f"Marks: {self.marks}\n"
                f"Average: {self.average():.2f} | Highest: {self.highest_subject()}\n"
                f"Status: {self.pass_or_fail()}\n")


class Topper(student):
    def __str__(self):
        return super().__str__() + "⭐ Topper\n"

    def motivational_quote(self):
        return f"{self.name} says: Hard work pays off!"
        
s1 = student("Shailaja", 1, {"math": 85, "science": 90, "english": 78})
s2 = student("Ravi", 2, {"math": 60, "science": 70, "english": 65})
s3 = student("Anu", 3, {"math": 95, "science": 92, "english": 88})

students = [s1, s2, s3]

top_student = max(students, key=lambda s: s.average())

topper = Topper(top_student.name, top_student.roll_no, top_student.marks)

for student in students:
    if student.roll_no == topper.roll_no:
        print(topper)
        print(topper.motivational_quote())
    else:
        print(student)    

        
        
        
            
    
            
            


--- Report Card ---
Name: Shailaja | Roll No: 1
Marks: {'math': 85, 'science': 90, 'english': 78}
Average: 84.33 | Highest: science
Status: Pass

--- Report Card ---
Name: Ravi | Roll No: 2
Marks: {'math': 60, 'science': 70, 'english': 65}
Average: 65.00 | Highest: science
Status: Pass

--- Report Card ---
Name: Anu | Roll No: 3
Marks: {'math': 95, 'science': 92, 'english': 88}
Average: 91.67 | Highest: math
Status: Pass
⭐ Topper

Anu says: Hard work pays off!


## Section 5: Conceptual Questions 

Answer these in your own words — no code needed, just understanding.

### Q15. Short Answers

**Write your answers below each question:**

**a) What is the difference between a class and an object?**

*Your answer:* class is a blueprint for creating objects which defines the state and behaviour of the objects by attributes and methods. 
Object is a real world entity which has a state and behaviour and is a instance of a class and there can be many objects for a single class.

**b) Why do we need `self` in every method? What would happen without it?**

*Your answer:* self is needed to refer to the current object in every method.If it is absent the attribute is treated like a local variable but not treat as a object attribute and can lead to misbehaviour when printed in some cases.

**c) What is the difference between `__init__` and a regular method?**

*Your answer:* __init__method initalizes the object with given parameters if present or intializes with default values mentioned in the method.

**d) Can a child class have attributes that the parent class doesn't? Give an example from the Employee system.**

*Your answer:* yes the child class can have attributes that the parent class don't have ex: In employee system the intern class which is a child class has an attribute mentor name.

**e) What is method overriding? Why is it useful?**

*Your answer:* method overriding is defining methods in the child class same as that of the parent class methods with  same name, different parameters and definition.
It is useful because it enables the child class more customised implementation and code reuse.

**f) If you run `dir(5)`, you see `__add__`, `__sub__`, `__mul__` etc. What does this tell you about how Python handles arithmetic?**

*Your answer:* Python has these methods for handling arithmetic operations specifically for the class<int> 

---

## Section 6: Git & GitHub 

Now that you've written real code, let's learn how to save and share it properly.

### Q17. Git Workflow — Practical Task

Do the following steps and **paste screenshots or the terminal output** in the markdown cell below:

1. Create a new folder called `oops-assignment`
2. Run `git init` inside it
3. Create a file `employee.py` with your Employee class from Q10
4. Run `git status` — what does it show?
5. Run `git add employee.py`
6. Run `git status` again — what changed?
7. Run `git commit -m "Add Employee class with inheritance"`
8. Run `git log` — paste the output

**Bonus:** Create a GitHub repository, push your code, and paste the repository link here.

**Paste your terminal outputs / screenshots here:**

```
# git status (before add): (base) user@user:~/oops-assignment$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	employee.py

nothing added to commit but untracked files present (use "git add" to track)



# git status (after add):
(base) user@user:~/oops-assignment$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   employee.py


# git log: 
(base) user@user:~/oops-assignment$ git log
commit a556becb90846f4734e19cf31e2bec9a7c346592 (HEAD -> master)
Author: shailajadurgam60-ai <shailajadurgam60@gmail.com>
Date:   Sun Mar 22 16:33:02 2026 +0530

    Add Employee class with inheritance

commit 3c361b5e49b4a7a2039a2a311c92c08a3e554c05
Author: shailajadurgam60-ai <shailajadurgam60@gmail.com>
Date:   Sun Mar 22 16:29:46 2026 +0530

    Add Employee class with inheritance





```

---

Bonus:GitHub repo link:https://github.com/shailajadurgam60-ai/OOPS-Assignment

### Q18. Git Scenario Questions

**a)** You accidentally committed a file with your password in it. The commit is already done but NOT pushed yet. How do you undo it?

*Your answer:* we can undo it by command  git reset HEAD~1 which removes the last commit.

**b)** You and your teammate both edited the same file. When you `git pull`, you get a "merge conflict." In simple terms, what happened and what should you do?

*Your answer:*A merge conflict happens when the same part of a file is modified by multiple people. It is resolved by manually editing the file and committing the correct version.

**c)** What is the difference between `git pull` and `git fetch`?

*Your answer:*git fetch downloads changes from the remote repository, while git pull downloads and automatically merges them into the local branch.”

**d)** Why should you write meaningful commit messages instead of `"fixed stuff"` or `"update"`?

*Your answer:* Meaningful commit messages clearly describe what changes were made, making it easier to understand, track, and maintain the project.

---

## Section 7: Reflection 

### Q19. Connect the Dots

**a)** Before this class, how did you think Python's `+` operator worked? How do you think about it now?

*Your answer:* I think the + operator worked on integers and does the arithmetic operation but after now i understood it actually serves as 
differently on different objects of special classes i.e differently for class <int> and class<str>.

**b)** You used `.upper()`, `.append()`, `.sort()` many times before. Did you ever think about WHERE these methods come from? What did the Cmd+Click demo in VS Code change for you?

*Your answer:* I thought these were Python's built-in string and list methods. The Cmd+Click showed me that these methods actual defintions and implementation and I realised that these methods are actually belongs to the classes and objects.

**c)** In your own words, explain to a non-coder friend: why do we need classes? Use the employee example.

*Your answer:* We need classes to store such huge data efficiently, like employee, manager, intern, like the employee class example, and we can create n no.of objects for the same class, defining the attributes and methods to perform any task for salary hike, bonus, or details, etc.
None of these can be done efficiently with other data types in Python, like list,dictionary,tuple etc. so we have custom data type classes and objects.Using which we can put the code and data together and perform any task easily in one line ex:e.calculate_bonus()

---

## Submission Instructions

1. Complete all sections in this notebook
2. **Restart Kernel & Run All** to make sure everything works
3. Save the notebook
4. Push to your GitHub repository with the commit message: `"Complete OOP & Inheritance Assignment"`
5. Share the GitHub repository link

> **Deadline:** *[To be announced by trainer]*

---

> *"Python's creators built `str` with `.upper()` and `list` with `.append()`. Today you built `Employee` with `.give_raise()`. You're a class designer now."* 