# Assignment: Classes, Objects & Inheritance in Python

> **Topics Covered:** Classes, Objects, Attributes, Methods, `__init__`, `self`, Inheritance, `super()`, Method Overriding 
> **Bonus Section:** Git & GitHub basics 
> **Difficulty:** Beginner to Intermediate 
> **Instructions:** 
> - Write your code in the cells provided below each question 
> - Run each cell to verify your output 
> - Some questions have **expected output** — match it exactly 
> - Questions marked are slightly harder — give them a shot! 
> - Submit it by Sunday Night !

---

## Section 1: Warm-Up — Everything is an Object 

These are quick questions to reinforce what you saw in class.

### Q1. Type Detective

Use `type()` to find the class/type of each value below. Print each result.

```
5
"hello"
3.14
[1, 2, 3]
True
{"name": "Rahul"}
(1, 2)
None
```

**What pattern do you notice in the output?**

In [1]:
# Your code here
print(
    type(5),
    type('hello'),
    type(3.14),
    type([1,2,3]),
    type(True),
    type({'name':'Samyu'}),
    type((1,2)),
    type(None),
    sep = "\n"
)
#every data type is a class

<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>
<class 'bool'>
<class 'dict'>
<class 'tuple'>
<class 'NoneType'>


### Q2. X-Ray Vision

Use `dir()` on a string `"python"` and answer:

1. How many methods does a string object have? (use `len()` on the `dir()` output)
2. Pick any **3 methods** you haven't used before, call them on `"python"`, and print the results
3. Use `help()` on one of those methods to read what it does

In [13]:
# Your code here
name = "python"
print(dir(name))
# 1. Total number of methods
print(len(dir(name)))
# 2. Try 3 new methods
print(name.encode())
print(name.casefold())
print(name.expandtabs())
# 3. Use help() on one method
help(str.translate)

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
80
b'python'
python
python
Help on 

### Q3. The Operator Secret

Without running the code first, **predict the output** of each line. Then run it to verify.

```python
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))
```

**In your own words:** Why does `+` behave differently for integers, strings, and lists?

In [16]:
# First write your predictions as comments, then run to verify

# (10).__add__(5) → I predict: 15
# "hello ".__add__("world") → I predict: hello world
# [1,2].__add__([3,4]) → I predict: [1,2,3,4]
# (10).__mul__(3) → I predict: 30
# "ha".__mul__(3) → I predict: hahaha

# Now run them:
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))

15
hello world
[1, 2, 3, 4]
30
hahaha


**Your explanation (why does `+` behave differently?):**

*Write here...*

---It behaves according to the object type because + is an overloaded operator 

## Section 2: Building Your First Classes 

### Q4. Create a `Book` class

Create a class called `Book` with:
- **Attributes:** `title`, `author`, `pages`, `price`
- **Method:** `get_summary()` → returns a string like: `"Atomic Habits by James Clear — 320 pages — ₹500"`

Then:
1. Create 3 book objects
2. Print the summary of each book
3. Print the `type()` of any one book object

**Expected output format:**
```
Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>
```

In [26]:
# Your code here
class Book:
    # replace this with your implementation
    def __init__(self,title,author,pages,price):
        self.title = title
        self.author = author
        self.pages = pages
        self.price = price
    def get_summary(self):
        return f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}"
    def __str__(self):
        return f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}"
    def apply_discount(self,percent):
        discount = (percent/100) * self.price
        self.price = self.price - discount
        print(f"Discount applied! New price of {self.title}: ₹{self.price}")
    def is_long_read(self):
        if self.pages > 400:
            return True
        else:
            return False
b1 = Book("Atomic Habits","James Clear",320,500)
b2 = Book("Deep Work","Cal Newport",296,590)
b3 = Book("Python Crash Course","Eric Matthes",544,600)
print(b1.get_summary())
print(b2.get_summary())
print(b3.get_summary())
print(type(b1))

Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹590
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>


### Q5. Add Behavior — `apply_discount()`

Add a method `apply_discount(percent)` to your `Book` class that:
- Reduces the price by the given percentage
- Prints: `"Discount applied! New price of 'Atomic Habits': ₹400"`

Also add a method `is_long_read()` that:
- Returns `True` if pages > 400, else `False`

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True
```

In [27]:
# Your code here
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read())

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read())

Discount applied! New price of Atomic Habits: ₹400.0
False
True


### Q6. The `__str__` Magic Method

Right now, if you `print(book_object)`, you get something ugly like `<__main__.Book object at 0x...>`.

Fix this by adding a `__str__` method to your Book class so that `print(book)` directly shows the summary.

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b) # Should print: Atomic Habits by James Clear — 320 pages — ₹500
```

**Hint:** Remember how `str` class has `__add__` for `+`? Similarly `__str__` controls what `print()` shows.

In [28]:
# Your code here
print(b)

Atomic Habits by James Clear — 320 pages — ₹400.0


###Q7. `BankAccount` Class

Create a `BankAccount` class with:
- **Attributes:** `owner`, `balance` (default 0)
- **Methods:**
 - `deposit(amount)` → adds to balance, prints confirmation
 - `withdraw(amount)` → subtracts from balance BUT prints `"Insufficient funds!"` if amount > balance
 - `get_balance()` → returns a formatted string: `"Rahul's balance: ₹5000"`

```python
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000
```

In [31]:
# Your code here
class BankAccount:
    def __init__(self,owner,balance=0):
        self.owner = owner
        self.balance = balance
    def deposit(self,amount):
        self.balance += amount
        print(f"Amount deposited! your current balance:{self.balance}")
    def withdraw(self,amount):
        if amount > self.balance:
            print("Insufficient funds!")
        else:
            self.balance -= amount
            print(f"Withdraw successfull! your current balance:{self.balance} ")
    def get_balance(self):
        return f"{self.owner}\'s balance:{self.balance}"
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) 
acc.withdraw(3000) 
acc.withdraw(20000)
print(acc.get_balance())

Amount deposited! your current balance:15000
Withdraw successfull! your current balance:12000 
Insufficient funds!
Rahul's balance:12000


### Q8. Parameter vs Attribute vs Argument

Look at this code and answer the questions below:

```python
class Car:
 def __init__(self, brand, speed):
 self.brand = brand
 self.top_speed = speed
 self.is_running = False
 
 def start(self):
 self.is_running = True

my_car = Car("Toyota", 180)
```

**Answer these in the markdown cell below:**
1. What are the **parameters** of `__init__`?
2. What are the **arguments** passed when creating `my_car`?
3. What are the **attributes** of a `Car` object?
4. What is the **method** in this class?
5. Why is `speed` a parameter but `top_speed` is an attribute? Are they the same thing?

**Your answers:**

1. Parameters:  self,brand,speed
2. Arguments: "Toyota",180
3. Attributes: brand,top_speed,is_running
4. Method: start
5. Explanation: speed is a parameter used temporarily in the __init__ method to receive a value when the object is created.
top_speed is an attribute stored inside the object using self.speed is just an input variable, while top_speed is the permanent data stored in the object.

---

## Section 3: Inheritance 

### Q9. `Animal` → `Dog` → `Cat`

Create a base class `Animal` with:
- **Attributes:** `name`, `sound`
- **Method:** `speak()` → returns `"<name> says <sound>!"`

Then create two child classes:
- `Dog(Animal)` — automatically sets sound to `"Woof"`, adds a method `fetch()` that returns `"<name> fetches the ball!"`
- `Cat(Animal)` — automatically sets sound to `"Meow"`, adds a method `purr()` that returns `"<name> purrs softly..."`

```python
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
```

In [41]:
# Your code here
class Animal:
    def __init__(self,name,sound):
        self.name = name
        self.sound = sound
    def speak(self):
        return f'{self.name} says {self.sound}!'
class Dog(Animal):
    def __init__(self,name,sound="Woof"):
        super().__init__(name, sound)
    def fetch(self):
        return f"{self.name} fetches the ball!"
class Cat(Animal):
    def __init__(self,name,sound="Meow"):
        super().__init__(name, sound)
    def purr(self):
        return f'{self.name} purrs softly...'

d = Dog("Bruno")
print(d.speak())
print(d.fetch())

c = Cat("Whiskers")
print(c.speak()) 
print(c.purr()) 

Bruno says Woof!
Bruno fetches the ball!
Whiskers says Meow!
Whiskers purrs softly...


### Q10. Employee Management — Full Hierarchy

Build the Employee system from class:

**Base class `Employee`:**
- Attributes: `name`, `emp_id`, `salary`, `department`
- Methods:
 - `get_details()` → `"[E001] Rahul | Engineering | ₹50000"`
 - `give_raise(amount)` → increases salary (only if amount > 0)
 - `calculate_bonus()` → returns 10% of salary

**Child class `Manager(Employee)`:**
- Extra attribute: `team_size`
- Override `calculate_bonus()` → returns 20% of salary
- New method: `approve_leave(emp_name)` → `"Priya approved leave for Rahul"`

**Child class `Intern(Employee)`:**
- Extra attribute: `mentor`
- Override `calculate_bonus()` → returns 5% of salary
- New method: `get_mentor()` → `"Amit's mentor is Priya"`

Then create a list of 5 employees (mix of Employee, Manager, Intern) and loop through them to print details and bonus for each.

**Expected output format:**
```
[E001] Rahul | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 → Bonus: ₹1000.0
...
```

In [42]:
# Your code here
class Employee:
    def __init__(self,name, emp_id, salary, dept):
        self.name = name
        self.emp_id = emp_id
        self.salary = salary
        self.dept = dept
    def get_details(self):
        return f"[{self.emp_id}] {self.name} | {self.dept} | ₹{self.salary}"
    def give_raise(self,amount):
        if amount > 0:
            self.salary += amount
    def calculate_bonus(self):
        return 0.1 * self.salary
class Manager(Employee):
    def __init__(self,name,emp_id,salary,dept,team_size):
        super().__init__(name,emp_id,salary,dept)
        self.team_size = team_size
    def  calculate_bonus(self):
        return 0.2 * self.salary
    def approve_leave(self,emp_name):
        return f'{self.name} approved leave for {emp_name}'
class Intern(Employee):
    def __init__(self,name,emp_id,salary,dept,mentor):
        super().__init__(name,emp_id,salary,dept)
        self.mentor = mentor
    def  calculate_bonus(self):
        return 0.05 * self.salary
    def get_mentor(self):
        return f"{self.name}\'s mentor is {self.mentor}"
        
employees = [
    Employee("Rahul", "E001", 50000, "Engineering"),
    Manager("Priya", "M001", 90000, "Engineering", 8),
    Intern("Amit", "I001", 20000, "Engineering", "Priya"),
    Employee("Neha", "E002", 45000, "Marketing"),
    Intern("Rohan", "I002", 18000, "Marketing", "Neha")
]

for emp in employees:
    print(f"{emp.get_details()} | Bonus: ₹{emp.calculate_bonus()}")  

[E001] Rahul | Engineering | ₹50000 | Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 | Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 | Bonus: ₹1000.0
[E002] Neha | Marketing | ₹45000 | Bonus: ₹4500.0
[I002] Rohan | Marketing | ₹18000 | Bonus: ₹900.0


### Q11. `isinstance()` Check

Using the employees list from Q10, write a loop that:
1. Prints `"Manager alert!"` for any Manager objects
2. Prints the mentor name for any Intern objects 
3. Just prints details for regular Employees

**Hint:** Use `isinstance(obj, ClassName)` to check the type.

In [47]:
# Your code here
for emp in employees:
    
    if isinstance(emp, Manager):
        print("Manager alert!")
        
    elif isinstance(emp, Intern):
        print(emp.get_mentor())
        
    elif isinstance(emp, Employee):
        print(emp.get_details())

[E001] Rahul | Engineering | ₹50000
Manager alert!
Amit's mentor is Priya
[E002] Neha | Marketing | ₹45000
Rohan's mentor is Neha


### Q12. The `super()` Deep Dive

Look at this code:

```python
class Vehicle:
 def __init__(self, brand, year):
 self.brand = brand
 self.year = year
 print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
 super().__init__(brand, year)
 self.battery_kwh = battery_kwh
 print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
```

**Answer these:**
1. What will be printed when `tesla` is created? (predict first, then run) 
2. 2. What does `super().__init__(brand, year)`
3. What would happen if you remove the `super()` line? Try it — what attributes does `tesla` have now?
4. Why do we pass `brand` and `year` to `super().__init__()` but NOT `battery_kwh`?

In [51]:
# Test your predictions here
class Vehicle:
    def __init__(self, brand, year):
        self.brand = brand
        self.year = year
        print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
    def __init__(self, brand, year, battery_kwh):
       # super().__init__(brand, year)
        self.battery_kwh = battery_kwh
        print(f"ElectricCar __init__ called for {brand}")
tesla = ElectricCar("Tesla", 2024, 75)

ElectricCar __init__ called for Tesla


**Your answers:**

1. Printed output:When the object is created, parent constructor runs first using super(), then the child constructor.
    Vehicle __init__ called for Tesla
    ElectricCar __init__ called for Tesla
2. What super() does: calls the constructor of the parent class and initializes the parent attributes.
3. Without super(): parent constructor will not run.So the attributes from parent class will not be created
4. Why not pass battery_kwh: battery_kwh is attribute of the electrician class itself but brand and year are the parent class attributes which we inherited

---

## Section 4: Challenge Problems

### Q13. Library System

Build a mini library:

**`Book` class:**
- Attributes: `title`, `author`, `is_available` (default True)

**`Library` class:**
- Attribute: `books` (an empty list to start)
- Methods:
 - `add_book(book)` → adds a Book object to the library
 - `show_available()` → prints only books where `is_available` is True
 - `lend_book(title)` → finds the book by title, sets `is_available = False`, prints confirmation. If not found or not available, print an error.
 - `return_book(title)` → finds the book, sets `is_available = True`
 - `search(keyword)` → returns all books where keyword is in the title OR author name (case-insensitive)

```python
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course
```

In [64]:
# Your code here
class Book:
    def __init__(self,title, author, is_available=True):
        self.title = title
        self.author = author
        self.is_available = is_available
    def __str__(self):
        return f'{self.title} by {self.author}'
class Library:
    def __init__(self,books=[]):
        self.books = books
    def add_book(self,book):
        self.books.append(book)
    def show_available(self):
        print("available books:")
        for book in self.books:
            if book.is_available:
                print(book)
                
    def lend_book(self,title):
        for book in self.books:
            if book.title == title:
                if book.is_available:
                    book.is_available = False
                    print(f"{title} has been lent successfully.")
                    return
                else:
                    print(f"{title} is not available.")
                    return
        print("Book not found.")
        
    def return_book(self,title):
        for book in self.books:
            if title == book.title:
                book.is_available = True
                print(f"{title} returned successfully.")
                return

    def search(self,keyword):
        keyword = keyword.lower()
        results = []
        for book in self.books:
            if keyword in book.title.lower() or keyword in book.author.lower():
                results.append(book)
        return results

lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")

available books:
Atomic Habits by James Clear
Deep Work by Cal Newport
Python Crash Course by Eric Matthes
Deep Work has been lent successfully.
available books:
Atomic Habits by James Clear
Python Crash Course by Eric Matthes
Deep Work is not available.
Deep Work returned successfully.


### Q14. School Report Card System

Build a system with:

**`Student` class:**
- Attributes: `name`, `roll_no`, `marks` (a dictionary like `{"math": 85, "science": 90, "english": 78}`)
- Methods:
 - `average()` → returns the average of all marks
 - `highest_subject()` → returns the subject with the highest mark
 - `pass_or_fail()` → returns `"Pass"` if average >= 40, else `"Fail"`
 - `__str__()` → nice formatted string

**`Topper(Student)` — inherits from Student:**
- Override `__str__()` to add a at the end
- New method: `motivational_quote()` → returns `"<name> says: Hard work pays off!"`

Create 3 students, find who has the highest average (the topper), and print everyone's report card.

**Expected output format:**
```
--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102 
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
Priya says: Hard work pays off!
```

In [67]:
# Your code here
class Student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

    def average(self):
        return sum(self.marks.values()) / len(self.marks)

    def highest_subject(self):
        return max(self.marks, key=self.marks.get)

    def pass_or_fail(self):
        return "Pass" if self.average() >= 40 else "Fail"

    def __str__(self):
        marks_str = ", ".join(f"{sub}={score}" for sub, score in self.marks.items())
        avg = round(self.average(), 2)
        highest = self.highest_subject()

        return (
            f"Name: {self.name} | Roll: {self.roll_no}\n"
            f"Marks: {marks_str}\n"
            f"Average: {avg} | Highest: {highest}\n"
            f"Status: {self.pass_or_fail()}\n"
        )


class Topper(Student):
    def __str__(self):
        return super().__str__() + "A"

    def motivational_quote(self):
        return f"{self.name} says: Hard work pays off!"



s1 = Student("Rahul", 101, {"math": 85, "science": 90, "english": 78})
s2 = Student("Priya", 102, {"math": 95, "science": 92, "english": 88})
s3 = Student("Amit", 103, {"math": 70, "science": 65, "english": 72})

students = [s1, s2, s3]


top_student = max(students, key=lambda s: s.average())


topper = Topper(top_student.name, top_student.roll_no, top_student.marks)

print("--- Report Card ---")

for s in students:
    if s.roll_no == topper.roll_no:
        print(topper)
        print(topper.motivational_quote())
    else:
        print(s)

--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
A
Priya says: Hard work pays off!
Name: Amit | Roll: 103
Marks: math=70, science=65, english=72
Average: 69.0 | Highest: english
Status: Pass



## Section 5: Conceptual Questions 

Answer these in your own words — no code needed, just understanding.

### Q15. Short Answers

**Write your answers below each question:**

**a) What is the difference between a class and an object?**

*Your answer:*Class is a blueprint or template used to create objects. Object is an instance of a class and represents a real world entity.

**b) Why do we need `self` in every method? What would happen without it?**

*Your answer:* self represents the current object. It is used to access the attributes and methods of that object. Without self, the method cannot access the object's variables and Python will raise an error.

**c) What is the difference between `__init__` and a regular method?**

*Your answer:* __init__ is a special method that runs automatically when an object is created. It is mainly used to initialize attributes. Regular methods do not run automatically and must be called explicitly.

**d) Can a child class have attributes that the parent class doesn't? Give an example from the Employee system.**

*Your answer:* Yes, a child class can have additional attributes that the parent class does not have. For example, in the Employee system the Manager class has the attribute team_size and the Intern class has the attribute mentor, which are not present in the Employee class

**e) What is method overriding? Why is it useful?**

*Your answer:*Method overriding means defining a method in the child class with the same name as the parent class method but with different behavior. It is useful because it allows the child class to provide its own implementation of a method

**f) If you run `dir(5)`, you see `__add__`, `__sub__`, `__mul__` etc. What does this tell you about how Python handles arithmetic?**

*Your answer:*It shows that arithmetic operations in Python are implemented using special methods. For example + calls __add__, - calls __sub__, and * calls __mul__. This means numbers are objects and arithmetic is handled through these methods.

---

## Section 6: Git & GitHub 

Now that you've written real code, let's learn how to save and share it properly.

### Q16. Git Basics — Theory

**Answer these:**

**a) What is the difference between Git and GitHub?**

*Your answer:*Git is a version control system used to track changes in code locally on your computer. GitHub is a cloud platform that hosts Git repositories online so people can store, share, and collaborate on projects.

**b) What do each of these commands do? Write one-line explanations:**

| Command | What it does |
|---------|-------------|
| `git init` | | Initializes a new Git repository in the current folder.
| `git add .` | | Adds all modified and new files in the current directory.
| `git commit -m "message"` | | Saves the changes with a message describing the update.
| `git status` | | Shows the current state of the repository (changed, staged, or untracked files).
| `git log` | | Displays the commit history of the repository.
| `git push` | | Uploads local commits to the github
| `git pull` | | Downloads changes from the github and merges them into the local repository
| `git clone <url>` | | Creates a copy of a repository on your local machine.

**c) What is a `.gitignore` file? Why would you add `__pycache__/` or `.env` to it?**

*Your answer:* .gitignore is a file used to tell Git which files or folders should not be tracked. We add __pycache__/ because it contains compiled Python files that are automatically generated and not needed in the repository. We add .env because it usually contains sensitive information like API keys or passwords.

**d) What is the difference between `git add .` and `git add filename.py`?**

*Your answer:* git add . adds all changed and new files in the current directory. git add filename.py adds only the specific file mentioned.

### Q17. Git Workflow — Practical Task

Do the following steps and **paste screenshots or the terminal output** in the markdown cell below:

1. Create a new folder called `oops-assignment`
2. Run `git init` inside it
3. Create a file `employee.py` with your Employee class from Q10
4. Run `git status` — what does it show?
5. Run `git add employee.py`
6. Run `git status` again — what changed?
7. Run `git commit -m "Add Employee class with inheritance"`
8. Run `git log` — paste the output

**Bonus:** Create a GitHub repository, push your code, and paste the repository link here.

**Paste your terminal outputs / screenshots here:**

```
# git status (before add):
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        employee.py

nothing added to commit but untracked files present (use "git add" to track)

# git status (after add):
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   employee.py

# git log: commit 3ed11e14028c0543f97f07ee495b106b3f1ae37f (HEAD -> master)
Author: SamhithaMada <madasamhithareddy@gmail.com>
Date:   Sun Mar 22 16:16:48 2026 +0530

    Add Employee class with inheritance


# GitHub repo link (bonus): 
https://github.com/SamhithaMada/oops-assignment
```

---

### Q18. Git Scenario Questions

**a)** You accidentally committed a file with your password in it. The commit is already done but NOT pushed yet. How do you undo it?

*Your answer:*You can undo the last commit using git reset HEAD~1. This removes the last commit but keeps the changes in the working directory so you can edit or remove the sensitive file before committing again.

**b)** You and your teammate both edited the same file. When you `git pull`, you get a "merge conflict." In simple terms, what happened and what should you do?

*Your answer:*It means both people modified the same part of the file and Git does not know which change to keep. You should open the file, manually resolve the conflict by choosing or combining the changes, then add and commit the resolved file.

**c)** What is the difference between `git pull` and `git fetch`?

*Your answer:*git pull downloads changes from the repository and automatically merges them into the local branch. git fetch only downloads the changes but does not merge them, allowing you to review them first

**d)** Why should you write meaningful commit messages instead of `"fixed stuff"` or `"update"`?

*Your answer:*Meaningful commit messages clearly describe what changes were made and why. This helps you and other developers understand the project history and makes debugging or tracking changes easier.

---

## Section 7: Reflection 

### Q19. Connect the Dots

**a)** Before this class, how did you think Python's `+` operator worked? How do you think about it now?

*Your answer:* Before this class I thought + was just used to add numbers or join strings. Now I understand that + actually calls a special method like __add__() depending on the object type, so different objects define their own behavior for the operator.

**b)** You used `.upper()`, `.append()`, `.sort()` many times before. Did you ever think about WHERE these methods come from? What did the Cmd+Click demo in VS Code change for you?

*Your answer:* Before I used these methods without thinking about where they come from. After the Cmd+Click demo in VS Code, I understood that these methods are defined inside the class of the object (like str or list). It showed that every object has its own methods defined in its class.

**c)** In your own words, explain to a non-coder friend: why do we need classes? Use the employee example.

*Your answer:* Classes help us organize data and behavior together. For example in an employee system, we can create an Employee class that stores information like name, id, salary, and department. Instead of writing separate code for each employee, we create objects from the class and reuse the same structure and methods for all employees.

---

## Submission Instructions

1. Complete all sections in this notebook
2. **Restart Kernel & Run All** to make sure everything works
3. Save the notebook
4. Push to your GitHub repository with the commit message: `"Complete OOP & Inheritance Assignment"`
5. Share the GitHub repository link

> **Deadline:** *[To be announced by trainer]*

---

> *"Python's creators built `str` with `.upper()` and `list` with `.append()`. Today you built `Employee` with `.give_raise()`. You're a class designer now."* 