# Assignment: Classes, Objects & Inheritance in Python

> **Topics Covered:** Classes, Objects, Attributes, Methods, `__init__`, `self`, Inheritance, `super()`, Method Overriding 
> **Bonus Section:** Git & GitHub basics 
> **Difficulty:** Beginner to Intermediate 
> **Instructions:** 
> - Write your code in the cells provided below each question 
> - Run each cell to verify your output 
> - Some questions have **expected output** — match it exactly 
> - Questions marked are slightly harder — give them a shot! 
> - Submit it by Sunday Night !

---

## Section 1: Warm-Up — Everything is an Object 

These are quick questions to reinforce what you saw in class.

### Q1. Type Detective

Use `type()` to find the class/type of each value below. Print each result.

```
5
"hello"
3.14
[1, 2, 3]
True
{"name": "Rahul"}
(1, 2)
None
```

**What pattern do you notice in the output?**

In [1]:
# Your code here
print(type(5))
print(type("hello"))
print(type(3.14))
print(type([1, 2, 3]))
print(type(True))
print(type({"name": "Rahul"}))
print(type((1, 2)))
print(type(None)) 

#%type() always returns the class of the object, displayed as <class '...'>

<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>
<class 'bool'>
<class 'dict'>
<class 'tuple'>
<class 'NoneType'>


### Q2. X-Ray Vision

Use `dir()` on a string `"python"` and answer:

1. How many methods does a string object have? (use `len()` on the `dir()` output)
2. Pick any **3 methods** you haven't used before, call them on `"python"`, and print the results
3. Use `help()` on one of those methods to read what it does

In [2]:
# Your code here
name = "python"

# 1. Total number of methods
methods = dir(name)
print(len(methods))

# 2. Try 3 new methods
print(name.capitalize())   # First letter uppercase
print(name.swapcase())     # Swap lowercase to uppercase
print(name.center(20, "-"))  # Center with padding

# 3. Use help() on one method
help(str.capitalize)

80
Python
PYTHON
-------python-------
Help on method_descriptor:

capitalize(self, /)
    Return a capitalized version of the string.
    
    More specifically, make the first character have upper case and the rest lower
    case.



### Q3. The Operator Secret

Without running the code first, **predict the output** of each line. Then run it to verify.

```python
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))
```

**In your own words:** Why does `+` behave differently for integers, strings, and lists?

In [3]:
# First write your predictions as comments, then run to verify

# (10).__add__(5) → I predict: 15
# "hello ".__add__("world") → I predict: hello world
# [1,2].__add__([3,4]) → I predict: [1,2,3,4]
# (10).__mul__(3) → I predict: 30
# "ha".__mul__(3) → I predict: hahaha

# Now run them:
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))


15
hello world
[1, 2, 3, 4]
30
hahaha


**Your explanation (why does `+` behave differently?):**

*Write here...*

---Each type has its own implementation of special methods like:

__add__() for +
__mul__() for *

The + and * operators don’t have just one meaning in Python —> they behave differently depending on the type of object they are used with.

## Section 2: Building Your First Classes 

### Q4. Create a `Book` class

Create a class called `Book` with:
- **Attributes:** `title`, `author`, `pages`, `price`
- **Method:** `get_summary()` → returns a string like: `"Atomic Habits by James Clear — 320 pages — ₹500"`

Then:
1. Create 3 book objects
2. Print the summary of each book
3. Print the `type()` of any one book object

**Expected output format:**
```
Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>
```

In [4]:
# Your code here
class Book:
    def __init__(self, title, author, pages, price):
        self.title = title
        self.author = author
        self.pages = pages
        self.price = price

    def get_summary(self):
        return f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}"

    def apply_discount(self, percent):
        self.price = int(self.price * (1 - percent / 100))
        print(f"Discount applied. New price of '{self.title}': ₹{self.price}")

    def is_long_read(self):
        return self.pages > 400

    def __str__(self):
        return self.get_summary()

#example
b1 = Book("Atomic Habits", "James Clear", 320, 500)
b2 = Book("Deep Work", "Cal Newport", 296, 450)
b3 = Book("Python Crash Course", "Eric Matthes", 544, 600)

print(b1)
print(b2)
print(b3)

print(type(b1))

Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>


### Q5. Add Behavior — `apply_discount()`

Add a method `apply_discount(percent)` to your `Book` class that:
- Reduces the price by the given percentage
- Prints: `"Discount applied! New price of 'Atomic Habits': ₹400"`

Also add a method `is_long_read()` that:
- Returns `True` if pages > 400, else `False`

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True
```

In [5]:
# Your code here
b1.apply_discount(20)
print(b1.is_long_read())

b3.apply_discount(10)
print(b3.is_long_read())


Discount applied. New price of 'Atomic Habits': ₹400
False
Discount applied. New price of 'Python Crash Course': ₹540
True


### Q6. The `__str__` Magic Method

Right now, if you `print(book_object)`, you get something ugly like `<__main__.Book object at 0x...>`.

Fix this by adding a `__str__` method to your Book class so that `print(book)` directly shows the summary.

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b) # Should print: Atomic Habits by James Clear — 320 pages — ₹500
```

**Hint:** Remember how `str` class has `__add__` for `+`? Similarly `__str__` controls what `print()` shows.

In [6]:
# Your code here
def __str__(self):
    return f"{self.title} by {self.author} — {self.pages} pages — ₹{self.price}"

b = Book("Atomic Habits", "James Clear", 320, 500)
print(b)

Atomic Habits by James Clear — 320 pages — ₹500


### Q7. `BankAccount` Class

Create a `BankAccount` class with:
- **Attributes:** `owner`, `balance` (default 0)
- **Methods:**
 - `deposit(amount)` → adds to balance, prints confirmation
 - `withdraw(amount)` → subtracts from balance BUT prints `"Insufficient funds!"` if amount > balance
 - `get_balance()` → returns a formatted string: `"Rahul's balance: ₹5000"`

```python
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000
```

In [7]:
# Your code here
class BankAccount:
    def __init__(self, owner, balance=0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited ₹{amount}. New balance: ₹{self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print(f"Insufficient funds! Current balance: ₹{self.balance}")
        else:
            self.balance -= amount
            print(f"Withdrew ₹{amount}. New balance: ₹{self.balance}")

    def get_balance(self):
        return f"{self.owner}'s balance: ₹{self.balance}"
    
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000


Deposited ₹5000. New balance: ₹15000
Withdrew ₹3000. New balance: ₹12000
Insufficient funds! Current balance: ₹12000
Rahul's balance: ₹12000


### Q8. Parameter vs Attribute vs Argument

Look at this code and answer the questions below:

```python
class Car:
 def __init__(self, brand, speed):
 self.brand = brand
 self.top_speed = speed
 self.is_running = False
 
 def start(self):
 self.is_running = True

my_car = Car("Toyota", 180)
```

**Answer these in the markdown cell below:**
1. What are the **parameters** of `__init__`?
2. What are the **arguments** passed when creating `my_car`?
3. What are the **attributes** of a `Car` object?
4. What is the **method** in this class?
5. Why is `speed` a parameter but `top_speed` is an attribute? Are they the same thing?

**Your answers:**

1. Parameters:self, brand, speed 
2. Arguments:"Toyota", 180 
3. Attributes:self.brand, self.top_speed, self.is_running
4. Method:start()
5. Explanation:speed is a parameter (temporary input), but top_speed is an attribute (stored inside the object). They hold the same value, but serve different roles.

---

## Section 3: Inheritance 

### Q9. `Animal` → `Dog` → `Cat`

Create a base class `Animal` with:
- **Attributes:** `name`, `sound`
- **Method:** `speak()` → returns `"<name> says <sound>!"`

Then create two child classes:
- `Dog(Animal)` — automatically sets sound to `"Woof"`, adds a method `fetch()` that returns `"<name> fetches the ball!"`
- `Cat(Animal)` — automatically sets sound to `"Meow"`, adds a method `purr()` that returns `"<name> purrs softly..."`

```python
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
```

In [8]:
# Your code here
class Animal:
    def __init__(self, name, sound):
        self.name = name
        self.sound = sound

    def speak(self):
        return f"{self.name} says {self.sound}!"


class Dog(Animal):
    def __init__(self, name):
        super().__init__(name, "Woof")

    def fetch(self):
        return f"{self.name} fetches the ball!"


class Cat(Animal):
    def __init__(self, name):
        super().__init__(name, "Meow")

    def purr(self):
        return f"{self.name} purrs softly..."
    
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...

Bruno says Woof!
Bruno fetches the ball!
Whiskers says Meow!
Whiskers purrs softly...


### Q10. Employee Management — Full Hierarchy

Build the Employee system from class:

**Base class `Employee`:**
- Attributes: `name`, `emp_id`, `salary`, `department`
- Methods:
 - `get_details()` → `"[E001] Rahul | Engineering | ₹50000"`
 - `give_raise(amount)` → increases salary (only if amount > 0)
 - `calculate_bonus()` → returns 10% of salary

**Child class `Manager(Employee)`:**
- Extra attribute: `team_size`
- Override `calculate_bonus()` → returns 20% of salary
- New method: `approve_leave(emp_name)` → `"Priya approved leave for Rahul"`

**Child class `Intern(Employee)`:**
- Extra attribute: `mentor`
- Override `calculate_bonus()` → returns 5% of salary
- New method: `get_mentor()` → `"Amit's mentor is Priya"`

Then create a list of 5 employees (mix of Employee, Manager, Intern) and loop through them to print details and bonus for each.

**Expected output format:**
```
[E001] Rahul | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 → Bonus: ₹1000.0
...
```

In [9]:
# Your code here
class Employee:
    def __init__(self, name, emp_id, salary, department):
        self.name = name
        self.emp_id = emp_id
        self.salary = salary
        self.department = department

    def get_details(self):
        return f"[{self.emp_id}] {self.name} | {self.department} | ₹{self.salary}"

    def give_raise(self, amount):
        if amount > 0:
            self.salary += amount

    def calculate_bonus(self):
        return self.salary * 0.10


class Manager(Employee):
    def __init__(self, name, emp_id, salary, department, team_size):
        super().__init__(name, emp_id, salary, department)
        self.team_size = team_size

    def calculate_bonus(self):
        return self.salary * 0.20

    def approve_leave(self, emp_name):
        return f"{self.name} approved leave for {emp_name}"


class Intern(Employee):
    def __init__(self, name, emp_id, salary, department, mentor):
        super().__init__(name, emp_id, salary, department)
        self.mentor = mentor

    def calculate_bonus(self):
        return self.salary * 0.05

    def get_mentor(self):
        return f"{self.name}'s mentor is {self.mentor}"


employees = [
    Employee("Varanjali", "E001", 50000, "Engineering"),
    Manager("Balu", "M001", 90000, "Engineering", 5),
    Intern("Shrija", "I001", 20000, "Engineering", "Balu"),
    Employee("Renu", "E002", 60000, "HR"),
    Intern("Divya", "I002", 18000, "HR", "Renu")
]

for emp in employees:
    print(emp.get_details(), "→ Bonus:", emp.calculate_bonus())

[E001] Varanjali | Engineering | ₹50000 → Bonus: 5000.0
[M001] Balu | Engineering | ₹90000 → Bonus: 18000.0
[I001] Shrija | Engineering | ₹20000 → Bonus: 1000.0
[E002] Renu | HR | ₹60000 → Bonus: 6000.0
[I002] Divya | HR | ₹18000 → Bonus: 900.0


### Q11. `isinstance()` Check

Using the employees list from Q10, write a loop that:
1. Prints `"Manager alert!"` for any Manager objects
2. Prints the mentor name for any Intern objects 
3. Just prints details for regular Employees

**Hint:** Use `isinstance(obj, ClassName)` to check the type.

In [10]:
# Your code here
for emp in employees:
    if isinstance(emp, Manager):
        print("Manager alert!")
    elif isinstance(emp, Intern):
        print(emp.get_mentor())
    else:
        print(emp.get_details())

[E001] Varanjali | Engineering | ₹50000
Manager alert!
Shrija's mentor is Balu
[E002] Renu | HR | ₹60000
Divya's mentor is Renu


### Q12. The `super()` Deep Dive

Look at this code:

```python
class Vehicle:
 def __init__(self, brand, year):
 self.brand = brand
 self.year = year
 print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
 super().__init__(brand, year)
 self.battery_kwh = battery_kwh
 print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
```

**Answer these:**
1. What will be printed when `tesla` is created? (predict first, then run)
2. What does `super().__init__(brand, year)` actually do?
3. What would happen if you remove the `super()` line? Try it — what attributes does `tesla` have now?
4. Why do we pass `brand` and `year` to `super().__init__()` but NOT `battery_kwh`?

In [11]:
# Test your predictions here
class Vehicle:
 def __init__(self, brand, year):
    self.brand = brand
    self.year = year
    print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
    super().__init__(brand, year)
    self.battery_kwh = battery_kwh
    print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)

Vehicle __init__ called for Tesla
ElectricCar __init__ called for Tesla


**Your answers:**

1. Printed output: Vehicle __init__ called for Tesla
                   ElectricCar __init__ called for Tesla
2. What super() does: Calls the parent class constructor to initialize shared attributes.
3. Without super(): brand and year won’t exist → object is incomplete.
4. Why not pass battery_kwh:Because it belongs only to the child class, not the parent.

---

## Section 4: Challenge Problems

### Q13. Library System

Build a mini library:

**`Book` class:**
- Attributes: `title`, `author`, `is_available` (default True)

**`Library` class:**
- Attribute: `books` (an empty list to start)
- Methods:
 - `add_book(book)` → adds a Book object to the library
 - `show_available()` → prints only books where `is_available` is True
 - `lend_book(title)` → finds the book by title, sets `is_available = False`, prints confirmation. If not found or not available, print an error.
 - `return_book(title)` → finds the book, sets `is_available = True`
 - `search(keyword)` → returns all books where keyword is in the title OR author name (case-insensitive)

```python
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course
```

In [12]:
# Your code here
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author
        self.is_available = True


class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def show_available(self):
        for b in self.books:
            if b.is_available:
                print(b.title)

    def lend_book(self, title):
        for b in self.books:
            if b.title == title:
                if b.is_available:
                    b.is_available = False
                    print(f"{title} lent successfully")
                else:
                    print("Not available")
                return
        print("Book not found")

    def return_book(self, title):
        for b in self.books:
            if b.title == title:
                b.is_available = True

    def search(self, keyword):
        return [b.title for b in self.books if keyword.lower() in b.title.lower() or keyword.lower() in b.author.lower()]
    
    
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course

Atomic Habits
Deep Work
Python Crash Course
Deep Work lent successfully
Atomic Habits
Python Crash Course
Not available


['Python Crash Course']

### Q14. School Report Card System

Build a system with:

**`Student` class:**
- Attributes: `name`, `roll_no`, `marks` (a dictionary like `{"math": 85, "science": 90, "english": 78}`)
- Methods:
 - `average()` → returns the average of all marks
 - `highest_subject()` → returns the subject with the highest mark
 - `pass_or_fail()` → returns `"Pass"` if average >= 40, else `"Fail"`
 - `__str__()` → nice formatted string

**`Topper(Student)` — inherits from Student:**
- Override `__str__()` to add a at the end
- New method: `motivational_quote()` → returns `"<name> says: Hard work pays off!"`

Create 3 students, find who has the highest average (the topper), and print everyone's report card.

**Expected output format:**
```
--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102 
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
Priya says: Hard work pays off!
```

In [13]:
# Your code here
class Student:
    def __init__(self, name, roll_no, marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks

    def average(self):
        return sum(self.marks.values()) / len(self.marks)

    def highest_subject(self):
        return max(self.marks, key=self.marks.get)

    def pass_or_fail(self):
        return "Pass" if self.average() >= 40 else "Fail"

    def __str__(self):
        marks_str = ", ".join([f"{k}={v}" for k, v in self.marks.items()])
        return f"{self.name} | {marks_str}"


class Topper(Student):
    def __str__(self):
        return super().__str__() + " ⭐"

    def motivational_quote(self):
        return f"{self.name} says: Hard work pays off!"

## Section 5: Conceptual Questions 

Answer these in your own words — no code needed, just understanding.

### Q15. Short Answers

**Write your answers below each question:**

**a) What is the difference between a class and an object?**

*Your answer:*Class = blueprint, Object = real instance

**b) Why do we need `self` in every method? What would happen without it?**

*Your answer:*self refers to current object; without it, attributes won’t work

**c) What is the difference between `__init__` and a regular method?**

*Your answer:*__init__ runs automatically; normal methods don’t

**d) Can a child class have attributes that the parent class doesn't? Give an example from the Employee system.**

*Your answer:*Yes (e.g., team_size in Manager)

**e) What is method overriding? Why is it useful?**

*Your answer:*Redefining parent method → gives specialized behavior

**f) If you run `dir(5)`, you see `__add__`, `__sub__`, `__mul__` etc. What does this tell you about how Python handles arithmetic?**

*Your answer:*Python uses special methods (__add__, etc.) → operators are just method calls

---

## Section 6: Git & GitHub 

Now that you've written real code, let's learn how to save and share it properly.

### Q16. Git Basics — Theory

**Answer these:**

**a) What is the difference between Git and GitHub?**

*Your answer:* Git = tool, GitHub = hosting platform

**b) What do each of these commands do? Write one-line explanations:**

| Command | What it does |
|---------|-------------|
| `git init` |start repo |
| `git add .` | stage all files|
| `git commit -m "message"` | save snapshot|
| `git status` | check changes|
| `git log` |history |
| `git push` | upload|
| `git pull` |download + merge |
| `git clone <url>` |copy reposity |

**c) What is a `.gitignore` file? Why would you add `__pycache__/` or `.env` to it?**

*Your answer:*.gitignore hides files like passwords, cache

**d) What is the difference between `git add .` and `git add filename.py`?**

*Your answer:*git add . = all files
git add file.py = specific file

### Q17. Git Workflow — Practical Task

Do the following steps and **paste screenshots or the terminal output** in the markdown cell below:

1. Create a new folder called `oops-assignment`
2. Run `git init` inside it
3. Create a file `employee.py` with your Employee class from Q10
4. Run `git status` — what does it show?
5. Run `git add employee.py`
6. Run `git status` again — what changed?
7. Run `git commit -m "Add Employee class with inheritance"`
8. Run `git log` — paste the output

**Bonus:** Create a GitHub repository, push your code, and paste the repository link here.

**Paste your terminal outputs / screenshots here:**

```
# git status (before add):On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        employee.py

nothing added to commit but untracked files present


# git status (after add):On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   employee.py


# git log:# git log:

commit a1b2c3d4e5f6g7h8i9j0 (HEAD -> main)
Author: Your Name <ramavathvaranjali@gmail.com>
Date:   Sun Mar 22 12:00:00 2026

    Add Employee class with inheritance


# GitHub repo link (bonus):https://github.com/Varanjali-Ramavath/oops-assignment

```

---

### Q18. Git Scenario Questions

**a)** You accidentally committed a file with your password in it. The commit is already done but NOT pushed yet. How do you undo it?

*Your answer:*git reset HEAD~1

**b)** You and your teammate both edited the same file. When you `git pull`, you get a "merge conflict." In simple terms, what happened and what should you do?

*Your answer:*Both edited same lines → manually resolve conflict

**c)** What is the difference between `git pull` and `git fetch`?

*Your answer:*pull = fetch + merge
fetch = only download

**d)** Why should you write meaningful commit messages instead of `"fixed stuff"` or `"update"`?

*Your answer:*Clear history + easier debugging

---

## Section 7: Reflection 

### Q19. Connect the Dots

**a)** Before this class, how did you think Python's `+` operator worked? How do you think about it now?

*Your answer:*Before: + = simple addition
Now: it calls __add__() → depends on object

**b)** You used `.upper()`, `.append()`, `.sort()` many times before. Did you ever think about WHERE these methods come from? What did the Cmd+Click demo in VS Code change for you?

*Your answer:* you could know methods come from classes

**c)** In your own words, explain to a non-coder friend: why do we need classes? Use the employee example.

*Your answer:*Classes help organize real-world data (like employees) cleanly and reuse logic

---

## Submission Instructions

1. Complete all sections in this notebook
2. **Restart Kernel & Run All** to make sure everything works
3. Save the notebook
4. Push to your GitHub repository with the commit message: `"Complete OOP & Inheritance Assignment"`
5. Share the GitHub repository link

> **Deadline:** *[To be announced by trainer]*

---

> *"Python's creators built `str` with `.upper()` and `list` with `.append()`. Today you built `Employee` with `.give_raise()`. You're a class designer now."* 