# Assignment: Classes, Objects & Inheritance in Python

> **Topics Covered:** Classes, Objects, Attributes, Methods, `__init__`, `self`, Inheritance, `super()`, Method Overriding 
> **Bonus Section:** Git & GitHub basics 
> **Difficulty:** Beginner to Intermediate 
> **Instructions:** 
> - Write your code in the cells provided below each question 
> - Run each cell to verify your output 
> - Some questions have **expected output** — match it exactly 
> - Questions marked are slightly harder — give them a shot! 
> - Submit it by Sunday Night !

---

## Section 1: Warm-Up — Everything is an Object 

These are quick questions to reinforce what you saw in class.

### Q1. Type Detective

Use `type()` to find the class/type of each value below. Print each result.

```
5
"hello"
3.14
[1, 2, 3]
True
{"name": "Rahul"}
(1, 2)
None
```

**What pattern do you notice in the output?**

In [1]:
# Your code here
a=5
str1="hello"
b=3.14
num=[1,2,3]
is_true=True
details={"name":"Rahul"}
set1=(1,2)
num2=None

print(type(a))
print(type(str1))
print(type(b))
print(type(num))
print(type(is_true))
print(type(details))
print(type(set1))
print(type(num2))



<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>
<class 'bool'>
<class 'dict'>
<class 'tuple'>
<class 'NoneType'>


### Q2. X-Ray Vision

Use `dir()` on a string `"python"` and answer:

1. How many methods does a string object have? (use `len()` on the `dir()` output)
2. Pick any **3 methods** you haven't used before, call them on `"python"`, and print the results
3. Use `help()` on one of those methods to read what it does

In [2]:
# Your code here
name = "python"

# 1. Total number of methods
print(dir(name))

# 2. Try 3 new methods
print(name.split())
print(name.center(20))
print(name.title())

# 3. Use help() on one method
print(help(name.upper))
print(help(name.strip))


['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
['python']
       python       
Pyt

### Q3. The Operator Secret

Without running the code first, **predict the output** of each line. Then run it to verify.

```python
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))
```

**In your own words:** Why does `+` behave differently for integers, strings, and lists?

In [3]:
# First write your predictions as comments, then run to verify

# (10).__add__(5) → I predict: 15
# "hello ".__add__("world") → I predict: hello world
# [1,2].__add__([3,4]) → I predict: [1,2,3,4]
# (10).__mul__(3) → I predict: 30
# "ha".__mul__(3) → I predict: hahaha

# Now run them:
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))


15
hello world
[1, 2, 3, 4]
30
hahaha


**Your explanation (why does `+` behave differently?):**

*Write here...*

here __add__() function defined as addition for integers and concatenation for Strings.Each datatype has its own implementataion of __add__().

## Section 2: Building Your First Classes 

### Q4. Create a `Book` class

Create a class called `Book` with:
- **Attributes:** `title`, `author`, `pages`, `price`
- **Method:** `get_summary()` → returns a string like: `"Atomic Habits by James Clear — 320 pages — ₹500"`

Then:
1. Create 3 book objects
2. Print the summary of each book
3. Print the `type()` of any one book object

**Expected output format:**
```
Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>
```

In [4]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.author=author
        self.pages=pages
        self.price=price
    def get_summary(self):
        return f"{self.title} by {self.author} - {self.pages} pages - {self.price}/-"

book1=Book("Atomic Habits","James Clear",320,500)
book2=Book("Deep Work","Cal Newport",296,450)
book3=Book("Python Crash","Eric Matthes",544,600)
print(book1.get_summary())
print(book2.get_summary())
print(book3.get_summary())

print(type(book3))


Atomic Habits by James Clear - 320 pages - 500/-
Deep Work by Cal Newport - 296 pages - 450/-
Python Crash by Eric Matthes - 544 pages - 600/-
<class '__main__.Book'>


### Q5. Add Behavior — `apply_discount()`

Add a method `apply_discount(percent)` to your `Book` class that:
- Reduces the price by the given percentage
- Prints: `"Discount applied! New price of 'Atomic Habits': ₹400"`

Also add a method `is_long_read()` that:
- Returns `True` if pages > 400, else `False`

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True
```

In [5]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.author=author
        self.pages=pages
        self.price=price
    def get_summary(self):
        return f"{self.title} by {self.author} - {self.pages} pages - {self.price}/-"

    def apply_discount(self,discount):
        return f"Discount applied! New price of '{self.title}':{(discount/100)*self.price}/-"
    def is_long_read(self):
        if self.pages>400:
            return True
        else:
            return False

book1=Book("Atomic Habits","James Clear",320,500)
book2=Book("Deep Work","Cal Newport",296,450)
book3=Book("Python Crash","Eric Matthes",544,600)
print(book1.get_summary())
print(book1.apply_discount(20))
print(book3.is_long_read())
print(book1)

Atomic Habits by James Clear - 320 pages - 500/-
Discount applied! New price of 'Atomic Habits':100.0/-
True


### Q6. The `__str__` Magic Method

Right now, if you `print(book_object)`, you get something ugly like `<__main__.Book object at 0x...>`.

Fix this by adding a `__str__` method to your Book class so that `print(book)` directly shows the summary.

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b) # Should print: Atomic Habits by James Clear — 320 pages — ₹500
```

**Hint:** Remember how `str` class has `__add__` for `+`? Similarly `__str__` controls what `print()` shows.

In [6]:
# Your code here
class Book:
    def __init__(self,title,author,pages,price):
        self.title=title
        self.author=author
        self.pages=pages
        self.price=price
    def get_summary(self):
        return f"{self.title} by {self.author} - {self.pages} pages - {self.price}/-"

    def apply_discount(self,discount):
        return f"Discount applied! New price of '{self.title}':{(discount/100)*self.price}/-"
    def is_long_read(self):
        if self.pages>400:
            return True
        else:
            return False

    def __str__(self):
        return f"{self.title} by {self.author} - {self.pages} pages - {self.price}/-"

book1=Book("Atomic Habits","James Clear",320,500)
book2=Book("Deep Work","Cal Newport",296,450)
book3=Book("Python Crash","Eric Matthes",544,600)

print(book1)
print(book2)
print(book3)


Atomic Habits by James Clear - 320 pages - 500/-
Deep Work by Cal Newport - 296 pages - 450/-
Python Crash by Eric Matthes - 544 pages - 600/-


### Q7. `BankAccount` Class

Create a `BankAccount` class with:
- **Attributes:** `owner`, `balance` (default 0)
- **Methods:**
 - `deposit(amount)` → adds to balance, prints confirmation
 - `withdraw(amount)` → subtracts from balance BUT prints `"Insufficient funds!"` if amount > balance
 - `get_balance()` → returns a formatted string: `"Rahul's balance: ₹5000"`

```python
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000
```

In [7]:
# Your code here
class BankAccount:
    def __init__(self,owner,balance):
        self.owner=owner
        self.balance=balance
    def deposit(self,amount):
        return f"Deposited {amount}/- . New Balance :{self.balance+amount}/-"

    def withdraw(self,amount):
        if amount>self.balance:
            return f"Insufficient funds! Current balance:{self.balance}/-"
        else:
            return f"Withdrew {amount}/- . New Balance :{self.balance-amount}/-"

    def get_balance(self):
        return f"{self.owner}'s balance:{self.balance}/-"

acc=BankAccount("Rahul",10000)
print(acc.deposit(5000))
print(acc.withdraw(3000))
print(acc.withdraw(20000))
print(acc.get_balance())
        

Deposited 5000/- . New Balance :15000/-
Withdrew 3000/- . New Balance :7000/-
Insufficient funds! Current balance:10000/-
Rahul's balance:10000/-


### Q8. Parameter vs Attribute vs Argument

Look at this code and answer the questions below:

```python
class Car:
 def __init__(self, brand, speed):
 self.brand = brand
 self.top_speed = speed
 self.is_running = False
 
 def start(self):
 self.is_running = True

my_car = Car("Toyota", 180)
```

**Answer these in the markdown cell below:**
1. What are the **parameters** of `__init__`?
2. What are the **arguments** passed when creating `my_car`?
3. What are the **attributes** of a `Car` object?
4. What is the **method** in this class?
5. Why is `speed` a parameter but `top_speed` is an attribute? Are they the same thing?

**Your answers:**

1. Parameters: self,brand,speed
2. Arguments: Toyota,180
3. Attributes: brand,top_speed,is_running
4. Method: start()
5. Explanation: speed is temporary variable ,cannot be accessed everywhere but top_speed is stored inside the object and accessible anytime using self.top_speed

---

## Section 3: Inheritance 

### Q9. `Animal` → `Dog` → `Cat`

Create a base class `Animal` with:
- **Attributes:** `name`, `sound`
- **Method:** `speak()` → returns `"<name> says <sound>!"`

Then create two child classes:
- `Dog(Animal)` — automatically sets sound to `"Woof"`, adds a method `fetch()` that returns `"<name> fetches the ball!"`
- `Cat(Animal)` — automatically sets sound to `"Meow"`, adds a method `purr()` that returns `"<name> purrs softly..."`

```python
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
```

In [8]:
# Your code here
class Animal:
    def __init__(self,name,sound):
        self.name=name
        self.sound=sound
    def speak(self):
        return f"{self.name} says {self.sound}"


class Dog(Animal):
    def __init__(self,name):
        super().__init__(name,"Woof")
    def fetch(self):
        return f"{self.name} fetches the ball"
    
    
class Cat(Animal):
    def __init__(self,name):
        super().__init__(name,"Meow")
    def purr(self):
        return f"{self.name} purrs softly"


d=Dog("Bruno")
print(d.fetch())
print(d.speak())

c=Cat("Whiskers")
print(c.speak())
print(c.purr())


Bruno fetches the ball
Bruno says Woof
Whiskers says Meow
Whiskers purrs softly


### Q10. Employee Management — Full Hierarchy

Build the Employee system from class:

**Base class `Employee`:**
- Attributes: `name`, `emp_id`, `salary`, `department`
- Methods:
 - `get_details()` → `"[E001] Rahul | Engineering | ₹50000"`
 - `give_raise(amount)` → increases salary (only if amount > 0)
 - `calculate_bonus()` → returns 10% of salary

**Child class `Manager(Employee)`:**
- Extra attribute: `team_size`
- Override `calculate_bonus()` → returns 20% of salary
- New method: `approve_leave(emp_name)` → `"Priya approved leave for Rahul"`

**Child class `Intern(Employee)`:**
- Extra attribute: `mentor`
- Override `calculate_bonus()` → returns 5% of salary
- New method: `get_mentor()` → `"Amit's mentor is Priya"`

Then create a list of 5 employees (mix of Employee, Manager, Intern) and loop through them to print details and bonus for each.

**Expected output format:**
```
[E001] Rahul | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 → Bonus: ₹1000.0
...
```

In [9]:
# Your code here
class Employee:
    def __init__(self,name,emp_id,salary,dept):
        self.name=name
        self.emp_id=emp_id
        self.salary=salary
        self.dept=dept
    def get_details(self):
        return f"[{self.emp_id}] {self.name} | {self.dept} | {self.salary}"
        
    def give_raise(self,amount):
        if(amount>0):
            self.salary=self.salary+amount

    def calculate_bonus(self):
        return (10/100)*self.salary

class Manager(Employee):
    def __init__(self,name,emp_id,salary,dept,team_size):
        super().__init__(name,emp_id,salary,dept)
        self.team_size=team_size

    def calculate_bonus(self):
        return (20/100)*self.salary

    def approve_leave(self,name):
        return f"{self.name} approved leave for {name}"

class Intern(Employee):
    def __init__(self,name,emp_id,salary,dept,mentor):
        super().__init__(name,emp_id,salary,dept)
        self.mentor=mentor
    def calculate_bonus(self):
        return (5/100)*self.salary
    def get_mentor(self,name):
        return f"{name} mentor is {self.name}"


employees = [
    Employee("Rahul", "E001", 50000, "Engineering"),
    Manager("Priya", "M001", 90000, "Engineering", 10),
    Intern("Amit", "I001", 20000, "Engineering", "Priya"),
    Employee("Sneha", "E002", 60000, "HR"),
    Manager("Arjun", "M002", 100000, "Finance", 8)
]

for emp in employees:
    print(f"{emp.get_details()} -> Bonus:{emp.calculate_bonus()}")


    
        

[E001] Rahul | Engineering | 50000 -> Bonus:5000.0
[M001] Priya | Engineering | 90000 -> Bonus:18000.0
[I001] Amit | Engineering | 20000 -> Bonus:1000.0
[E002] Sneha | HR | 60000 -> Bonus:6000.0
[M002] Arjun | Finance | 100000 -> Bonus:20000.0


### Q11. `isinstance()` Check

Using the employees list from Q10, write a loop that:
1. Prints `"Manager alert!"` for any Manager objects
2. Prints the mentor name for any Intern objects 
3. Just prints details for regular Employees

**Hint:** Use `isinstance(obj, ClassName)` to check the type.

In [10]:
# Your code here
for emp in employees:
    if isinstance(emp,Manager):
        print("Manager alert!")
    elif isinstance(emp,Intern):
        print(f"Mentor:{emp.name}")
    else:
        print(f"{emp.get_details()}")
        

[E001] Rahul | Engineering | 50000
Manager alert!
Mentor:Amit
[E002] Sneha | HR | 60000
Manager alert!


### Q12. The `super()` Deep Dive

Look at this code:

```python
class Vehicle:
 def __init__(self, brand, year):
 self.brand = brand
 self.year = year
 print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
 super().__init__(brand, year)
 self.battery_kwh = battery_kwh
 print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
```

**Answer these:**
1. What will be printed when `tesla` is created? (predict first, then run)
2. What does `super().__init__(brand, year)` actually do?
3. What would happen if you remove the `super()` line? Try it — what attributes does `tesla` have now?
4. Why do we pass `brand` and `year` to `super().__init__()` but NOT `battery_kwh`?

In [11]:
# Test your predictions here
class Vehicle:
    def __init__(self, brand, year):
        self.brand = brand
        self.year = year
        print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
    def __init__(self, brand, year, battery_kwh):
        super().__init__(brand, year)
        self.battery_kwh = battery_kwh
        print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)


Vehicle __init__ called for Tesla
ElectricCar __init__ called for Tesla


**Your answers:**

1. Printed output: Vehicle __init_called for Tesla
2. What super() does:It calls the parent class constructor
3. Without super(): Ear __init__ called for Tesla Printed
4. Why not pass battery_kwh: battery_kwh attribute is handled by the child class.so it is not passed to super().__init__

---

## Section 4: Challenge Problems

### Q13. Library System

Build a mini library:

**`Book` class:**
- Attributes: `title`, `author`, `is_available` (default True)

**`Library` class:**
- Attribute: `books` (an empty list to start)
- Methods:
 - `add_book(book)` → adds a Book object to the library
 - `show_available()` → prints only books where `is_available` is True
 - `lend_book(title)` → finds the book by title, sets `is_available = False`, prints confirmation. If not found or not available, print an error.
 - `return_book(title)` → finds the book, sets `is_available = True`
 - `search(keyword)` → returns all books where keyword is in the title OR author name (case-insensitive)

```python
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course
```

In [12]:
class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author
        self.is_available = True


class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def show_available(self):
        for b in self.books:
            if b.is_available:
                print(f"{b.title} by {b.author}")

    def lend_book(self, title):
        found = False
        for b in self.books:
            if title == b.title:
                if b.is_available:
                    b.is_available = False
                    print("Book was lent")
                else:
                    print("Book already lent")
                found = True
                break

        if not found:
            print("Book not found")

    def return_book(self, title):
        found = False
        for b in self.books:
            if title == b.title:
                b.is_available = True
                print("Book returned")
                found = True
                break

        if not found:
            print("Book not found")

    def search(self, word):
        found = False
        for b in self.books:
            if word.lower() in b.title.lower() or word.lower() in b.author.lower():
                print(f"{b.title} by {b.author}")
                found = True

        if not found:
            print("No matching books found")


lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
print("----")
lib.lend_book("Deep Work")
lib.show_available()
print("----")
lib.lend_book("Deep Work")
lib.return_book("Deep Work")
print("----")
lib.search("python")

Atomic Habits by James Clear
Deep Work by Cal Newport
Python Crash Course by Eric Matthes
----
Book was lent
Atomic Habits by James Clear
Python Crash Course by Eric Matthes
----
Book already lent
Book returned
----
Python Crash Course by Eric Matthes


### Q14. School Report Card System

Build a system with:

**`Student` class:**
- Attributes: `name`, `roll_no`, `marks` (a dictionary like `{"math": 85, "science": 90, "english": 78}`)
- Methods:
 - `average()` → returns the average of all marks
 - `highest_subject()` → returns the subject with the highest mark
 - `pass_or_fail()` → returns `"Pass"` if average >= 40, else `"Fail"`
 - `__str__()` → nice formatted string

**`Topper(Student)` — inherits from Student:**
- Override `__str__()` to add a at the end
- New method: `motivational_quote()` → returns `"<name> says: Hard work pays off!"`

Create 3 students, find who has the highest average (the topper), and print everyone's report card.

**Expected output format:**
```
--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102 
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
Priya says: Hard work pays off!
```

In [24]:
# Your code here
class Student:
    def __init__(self,name,roll_no,marks):
        self.name=name
        self.roll_no=roll_no
        self.marks=marks

    def average(self):
        sum=0;
        for m in self.marks:
            sum+=self.marks[m]

        return sum/len(self.marks)

    def highest_subject(self):
        maxi=0
        sub=""
        for m in self.marks:
            if self.marks[m]>maxi:
                maxi=self.marks[m]
                sub=m
        return sub

    def pass_or_fail(self):
        if self.average()>40:
            return "Pass"
        else:
            return "Fail"

    def __str__(self):
        return f"--- Report Card ---\nName: {self.name} | {self.roll_no}\nMarks: {self.marks}\nAverage: {self.average()} | Highest: {self.highest_subject()}\nStatus: {self.pass_or_fail()}\n"

class Topper(Student):
    def motivational_quote(self):
        return f"{self.name} says :Hard work never Fails"

    def __str__(self):
        return self.motivational_quote()


s1=Student("Priya",101,{"math": 85, "science": 90, "english": 78})
s2=Student("Rahul",102,{"math": 90, "science": 78, "english": 87})
s3=Student("Srinipa",103,{"math": 85, "science": 90, "english": 100})

print(s1)
print(s3)

for s in [s1,s2,s3]:
    average=0;
    if s.average()>average:
        average=s.average()
        ss=s


print(Topper(ss.name,ss.roll_no,ss.marks))



        

--- Report Card ---
Name: Priya | 101
Marks: {'math': 85, 'science': 90, 'english': 78}
Average: 84.33333333333333 | Highest: science
Status: Pass

--- Report Card ---
Name: Srinipa | 103
Marks: {'math': 85, 'science': 90, 'english': 100}
Average: 91.66666666666667 | Highest: english
Status: Pass

Srinipa says :Hard work never Fails


## Section 5: Conceptual Questions 

Answer these in your own words — no code needed, just understanding.

### Q15. Short Answers

**Write your answers below each question:**

**a) What is the difference between a class and an object?**

*Your answer:*A class is a blueprint or template used to create objects, while an object is an instance of a class that contains actual data and can use the class’s methods.

**b) Why do we need `self` in every method? What would happen without it?**

*Your answer:*selfis used to differentiate between instance variables and local variables

**c) What is the difference between `__init__` and a regular method?**

*Your answer:*__init__ is a special constructor method that is automatically called when an object is created, used to initialize attributes.A regular method is called explicitly to perform certain tasks.

**d) Can a child class have attributes that the parent class doesn't? Give an example from the Employee system.**

*Your answer:*Yes, a child class can have its own additional attributes.In an Employee system, a Manager class (child) can have an extra attribute like team_size that is not present in the Employee (parent) class.

**e) What is method overriding? Why is it useful?**

*Your answer:*Method overriding is when a child class provides a different implementation of a method that is already defined in the parent class. It is useful to customize or modify behavior for specific cases.

**f) If you run `dir(5)`, you see `__add__`, `__sub__`, `__mul__` etc. What does this tell you about how Python handles arithmetic?**

*Your answer:*It shows that Python treats numbers as objects and arithmetic operations are performed using special methods like __add__ and __sub__.

---

## Section 6: Git & GitHub 

Now that you've written real code, let's learn how to save and share it properly.

### Q16. Git Basics — Theory

**Answer these:**

**a) What is the difference between Git and GitHub?**

*Your answer:* Git is a version control system used to track changes in code locally, while GitHub is an online platform used to store, share, and collaborate on Git repositories.

**b) What do each of these commands do? Write one-line explanations:**

| Command | What it does |
|---------|-------------|
| `git init` | Initializes a new Git repository in a folder|
| `git add .` | Adds all files to the staging area|
| `git commit -m "message"` |Saves the staged changes with a message |
| `git status` |Shows the current state of files |
| `git log` | Displays commit history|
| `git push` |Uploads local commits to a remote repository |
| `git pull` | Downloads and merges changes from a remote repository|
| `git clone <url>` |Copies a remote repository to your local system |

**c) What is a `.gitignore` file? Why would you add `__pycache__/` or `.env` to it?**

*Your answer:*.gitignore file tells Git which files or folders to ignore and not track.

**d) What is the difference between `git add .` and `git add filename.py`?**

*Your answer:* git add . adds all files in the folder to staging, while git add filename.py adds only that specific file.

### Q17. Git Workflow — Practical Task

Do the following steps and **paste screenshots or the terminal output** in the markdown cell below:

1. Create a new folder called `oops-assignment`
2. Run `git init` inside it
3. Create a file `employee.py` with your Employee class from Q10
4. Run `git status` — what does it show?
5. Run `git add employee.py`
6. Run `git status` again — what changed?
7. Run `git commit -m "Add Employee class with inheritance"`
8. Run `git log` — paste the output

**Bonus:** Create a GitHub repository, push your code, and paste the repository link here.

**Paste your terminal outputs / screenshots here:**

```
# git status (before add):
On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	employee.py

nothing added to commit but untracked files present (use "git add" to track)


# git status (after add):
On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   employee.py


# git log:
commit aa65a35a21fa1e809dc1fc0ef158673222754e8a (HEAD -> main)
Author: Anushakaringula <karingulaanushareddy@gmail.com>
Date:   Mon Mar 23 18:59:23 2026 +0530

    add employee.py



# GitHub repo link (bonus):
https://github.com/Anushakaringula/oop_assignment.git
```

---

### Q18. Git Scenario Questions

**a)** You accidentally committed a file with your password in it. The commit is already done but NOT pushed yet. How do you undo it?

*Your answer:* Use git reset --soft HEAD~1 to undo the last commit while keeping changes, or git reset --hard HEAD~1 to completely remove it.

**b)** You and your teammate both edited the same file. When you `git pull`, you get a "merge conflict." In simple terms, what happened and what should you do?

*Your answer:* A merge conflict happens when two people edit the same part of a file. Git cannot decide which change to keep, so you must manually edit the file, resolve the conflict, and commit again.

**c)** What is the difference between `git pull` and `git fetch`?

*Your answer:* git pull fetches and automatically merges changes, while git fetch only downloads changes without merging.

**d)** Why should you write meaningful commit messages instead of `"fixed stuff"` or `"update"`?

*Your answer:* Meaningful commit messages help understand what changes were made, making it easier to track, debug, and collaborate with others.

---

## Section 7: Reflection 

### Q19. Connect the Dots

**a)** Before this class, how did you think Python's `+` operator worked? How do you think about it now?

*Your answer:* Before, I thought + directly adds numbers. Now I understand that Python internally calls special methods like __add__() to perform the operation.

**b)** You used `.upper()`, `.append()`, `.sort()` many times before. Did you ever think about WHERE these methods come from? What did the Cmd+Click demo in VS Code change for you?

*Your answer:* Earlier, I used these methods without thinking about their origin. The Cmd+Click demo showed that these methods are defined inside classes, which helped me understand that everything in Python is object-oriented.

**c)** In your own words, explain to a non-coder friend: why do we need classes? Use the employee example.

*Your answer:* Classes help us organize data and behavior together. For example, in an employee system, a class defines common properties like name and salary, and each employee object represents a real person with those details.

---

## Submission Instructions

1. Complete all sections in this notebook
2. **Restart Kernel & Run All** to make sure everything works
3. Save the notebook
4. Push to your GitHub repository with the commit message: `"Complete OOP & Inheritance Assignment"`
5. Share the GitHub repository link

> **Deadline:** *[To be announced by trainer]*

---

> *"Python's creators built `str` with `.upper()` and `list` with `.append()`. Today you built `Employee` with `.give_raise()`. You're a class designer now."* 