# Assignment: Classes, Objects & Inheritance in Python

> **Topics Covered:** Classes, Objects, Attributes, Methods, `__init__`, `self`, Inheritance, `super()`, Method Overriding
> **Bonus Section:** Git & GitHub basics
> **Difficulty:** Beginner to Intermediate
> **Instructions:**
> - Write your code in the cells provided below each question
> - Run each cell to verify your output
> - Some questions have **expected output** — match it exactly
> - Questions marked are slightly harder — give them a shot!
> - Submit it by Sunday Night !

---

## Section 1: Warm-Up — Everything is an Object

These are quick questions to reinforce what you saw in class.

### Q1. Type Detective

Use `type()` to find the class/type of each value below. Print each result.

```
5
"hello"
3.14
[1, 2, 3]
True
{"name": "Rahul"}
(1, 2)
None
```

**What pattern do you notice in the output?**

In [1]:
# Your code here
print(type(5))
print(type("hello"))
print(type(3.14))
print(type([1, 2, 3]))
print(type(True))
print(type({"name": "Rahul"}))
print(type((1, 2)))
print(type(None))

<class 'int'>
<class 'str'>
<class 'float'>
<class 'list'>
<class 'bool'>
<class 'dict'>
<class 'tuple'>
<class 'NoneType'>


**Pattern:** <class 'type_name'>

All the values in python are objects.Every object belongs to a class.

### Q2. X-Ray Vision

Use `dir()` on a string `"python"` and answer:

1. How many methods does a string object have? (use `len()` on the `dir()` output)
2. Pick any **3 methods** you haven't used before, call them on `"python"`, and print the results
3. Use `help()` on one of those methods to read what it does

In [13]:
# Your code here
name = "python"
print(dir(name))

# 1. Total number of methods
print(len(dir(name)))

# 2. Pick any 3 methods
print(name.replace("p","P"))
print(name.find("lo"))
print(name.__contains__("th"))

# 2. Try 3 new methods
print(name.__add__(" Assignment")) #temporary concatenation
print(name)
print(name.__len__())
print(name.split("h")) #splitting string into list of strings
print(name)
print(name.__getitem__(2))

# 3. Use help() on one method

print(help(name.upper))
print(help(name.__add__))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
81
Python
-1
True
p

Methods starting with __ = special methods (dunder methods)

| What you write | What Python actually does |
| -------------- | ------------------------- |
| `"a" + "b"`    | `"a".__add__("b")`        |
| `len("hi")`    | `"hi".__len__()`          |
| `"a" in "cat"` | `"cat".__contains__("a")` |
| `"abc"[1]`     | `"abc".__getitem__(1)`    |


### Q3. The Operator Secret

Without running the code first, **predict the output** of each line. Then run it to verify.

```python
print((10).__add__(5)) #15
print("hello ".__add__("world")) #hello world
print([1,2].__add__([3,4]))#[1,2,3,4]
print((10).__mul__(3))#10*3=30
print("ha".__mul__(3))#hahaha
```

**In your own words:** Why does `+` behave differently for integers, strings, and lists?


In [14]:
# First write your predictions as comments, then run to verify

# (10).__add__(5) → I predict: 15
# "hello ".__add__("world") → I predict: hello world
# [1,2].__add__([3,4]) → I predict: [1,2,3,4]
# (10).__mul__(3) → I predict: 30
# "ha".__mul__(3) → I predict: hahaha

# Now run them:
print((10).__add__(5))
print("hello ".__add__("world"))
print([1,2].__add__([3,4]))
print((10).__mul__(3))
print("ha".__mul__(3))


15
hello world
[1, 2, 3, 4]
30
hahaha


**Your explanation (why does `+` behave differently?):**

*Internally when + is used python calls dunder method `.__add__()` .It is method which is defined in evry class.According to datatype like int,strings, lists the behaviour of the method changes.*

---

## Section 2: Building Your First Classes

### Q4. Create a `Book` class

Create a class called `Book` with:
- **Attributes:** `title`, `author`, `pages`, `price`
- **Method:** `get_summary()` → returns a string like: `"Atomic Habits by James Clear — 320 pages — ₹500"`

Then:
1. Create 3 book objects
2. Print the summary of each book
3. Print the `type()` of any one book object

**Expected output format:**
```
Atomic Habits by James Clear — 320 pages — ₹500
Deep Work by Cal Newport — 296 pages — ₹450
Python Crash Course by Eric Matthes — 544 pages — ₹600
<class '__main__.Book'>
```

In [17]:
# Your code here
class Book:
 def __init__(self, title, author, pages, price):
  self.title = title
  self.author = author
  self.pages = pages
  self.price = price
 def get_summary(self):
  return f"{self.title} by {self.author} - {self.pages} pages - Rs.{self.price}"

book1=Book("Atomic Habits", "James Clear", 320, 500)
book2=Book("Deep Work", "Cal Newport", 296, 450)
book3=Book("Python Crash Course", "Eric Matthes", 544, 600)

print(book1.get_summary())
print(book2.get_summary())
print(book3.get_summary())

print(type(book1))

Atomic Habits by James Clear - 320 pages - Rs.500
Deep Work by Cal Newport - 296 pages - Rs.450
Python Crash Course by Eric Matthes - 544 pages - Rs.600
<class '__main__.Book'>


### Q5. Add Behavior — `apply_discount()`

Add a method `apply_discount(percent)` to your `Book` class that:
- Reduces the price by the given percentage
- Prints: `"Discount applied! New price of 'Atomic Habits': ₹400"`

Also add a method `is_long_read()` that:
- Returns `True` if pages > 400, else `False`

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True
```

In [19]:
# Your code here
class Book:
 def __init__(self, title, author, pages, price):
  self.title = title
  self.author = author
  self.pages = pages
  self.price = price
 def get_summary(self):
  return f"{self.title} by {self.author} - {self.pages} pages - Rs.{self.price}"
 def apply_discount(self, percent):
  if percent>0:
    self.price-=(self.price*percent)/100
    print(f"Discount applied! New price of '{self.title}': Rs.{self.price}")
  else:
    print("Invalid discount percentage!")
 def is_long_read(self):
  if self.pages>400:
    return True
  else:
    return False
b = Book("Atomic Habits", "James Clear", 320, 500)
b.apply_discount(20)
print(b.is_long_read()) # False

b2 = Book("Python Crash Course", "Eric Matthes", 544, 600)
print(b2.is_long_read()) # True

Discount applied! New price of 'Atomic Habits': Rs.400.0
False
True


### Q6. The `__str__` Magic Method

Right now, if you `print(book_object)`, you get something ugly like `<__main__.Book object at 0x...>`.

Fix this by adding a `__str__` method to your Book class so that `print(book)` directly shows the summary.

```python
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b) # Should print: Atomic Habits by James Clear — 320 pages — ₹500
```

**Hint:** Remember how `str` class has `__add__` for `+`? Similarly `__str__` controls what `print()` shows.

In [22]:
# Your code here
class Book:
 def __init__(self, title, author, pages, price):
  self.title = title
  self.author = author
  self.pages = pages
  self.price = price
 def get_summary(self):
  return f"{self.title} by {self.author} - {self.pages} pages - Rs.{self.price}"
 def apply_discount(self, percent):
  if percent>0:
    self.price-=(self.price*percent)/100
    print(f"Discount applied! New price of '{self.title}': Rs.{self.price}")
  else:
    print("Invalid discount percentage!")
 def is_long_read(self):
  if self.pages>400:
    return True
  else:
    return False
 def __str__(self):
  return self.get_summary()
b = Book("Atomic Habits", "James Clear", 320, 500)
print(b)

Atomic Habits by James Clear - 320 pages - Rs.500


### Q7. `BankAccount` Class

Create a `BankAccount` class with:
- **Attributes:** `owner`, `balance` (default 0)
- **Methods:**
 - `deposit(amount)` → adds to balance, prints confirmation
 - `withdraw(amount)` → subtracts from balance BUT prints `"Insufficient funds!"` if amount > balance
 - `get_balance()` → returns a formatted string: `"Rahul's balance: ₹5000"`

```python
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000
```

In [24]:
# Your code here
class BankAccount:
 def __init__(self, owner, balance=0):
  self.owner = owner
  self.balance = balance
 def deposit(self, amount):
  if amount>0:
    self.balance+=amount
    print(f"Deposited Rs.{amount}. New balance: Rs.{self.balance}")
  else:
    print("Invalid deposit amount!")
 def withdraw(self, amount):
  if amount>0:
    if amount<=self.balance:
      print(f"Withdrwan Rs.{amount}. New balance: Rs.{self.balance}")
    else:
      print(f"Insufficient funds! Current balance: Rs.{self.balance}")
  else:
    print("Invalid withdrawal amount!")
 def get_balance(self):
  return f"{self.owner}'s balance: Rs.{self.balance}"
acc = BankAccount("Rahul", 10000)
acc.deposit(5000) # Deposited ₹5000. New balance: ₹15000
acc.withdraw(3000) # Withdrew ₹3000. New balance: ₹12000
acc.withdraw(20000) # Insufficient funds! Current balance: ₹12000
print(acc.get_balance()) # Rahul's balance: ₹12000

Deposited Rs.5000. New balance: Rs.15000
Withdrwan Rs.3000. New balance: Rs.15000
Insufficient funds! Current balance: Rs.15000
Rahul's balance: Rs.15000


### Q8. Parameter vs Attribute vs Argument

Look at this code and answer the questions below:

```python
class Car:
 def __init__(self, brand, speed):
 self.brand = brand
 self.top_speed = speed
 self.is_running = False

 def start(self):
 self.is_running = True

my_car = Car("Toyota", 180)
```

**Answer these in the markdown cell below:**
1. What are the **parameters** of `__init__`?
2. What are the **arguments** passed when creating `my_car`?
3. What are the **attributes** of a `Car` object?
4. What is the **method** in this class?
5. Why is `speed` a parameter but `top_speed` is an attribute? Are they the same thing?

**Your answers:**

1. Parameters: self, brand, speed
2. Arguments: "Toayato", 180
3. Attributes: brand,top_speed,is_running
4. Method: start()
5. Explanation: top_speed belongs to self i.e, class. top_speed is a feature that all the objects of that class have , where as speed is just a parameter which holds a value hich is sent by user during fun call or object creation.

---

## Section 3: Inheritance

### Q9. `Animal` → `Dog` → `Cat`

Create a base class `Animal` with:
- **Attributes:** `name`, `sound`
- **Method:** `speak()` → returns `"<name> says <sound>!"`

Then create two child classes:
- `Dog(Animal)` — automatically sets sound to `"Woof"`, adds a method `fetch()` that returns `"<name> fetches the ball!"`
- `Cat(Animal)` — automatically sets sound to `"Meow"`, adds a method `purr()` that returns `"<name> purrs softly..."`

```python
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...
```

In [25]:
# Your code here
class Animal:
 def __init__(self, name, sound):
  self.name = name
  self.sound = sound
 def speak(self):
  return f"{self.name} says {self.sound}!"
class Dog(Animal):
 def __init__(self, name):
  super().__init__(name, "Woof")
 def fetch(self):
  return f"{self.name} fetches the ball!"
class Cat(Animal):
 def __init__(self, name):
  super().__init__(name, "Meow")
 def purr(self):
  return f"{self.name} purrs softly..."
d = Dog("Bruno")
print(d.speak()) # Bruno says Woof!
print(d.fetch()) # Bruno fetches the ball!

c = Cat("Whiskers")
print(c.speak()) # Whiskers says Meow!
print(c.purr()) # Whiskers purrs softly...

Bruno says Woof!
Bruno fetches the ball!
Whiskers says Meow!
Whiskers purrs softly...


### Q10. Employee Management — Full Hierarchy

Build the Employee system from class:

**Base class `Employee`:**
- Attributes: `name`, `emp_id`, `salary`, `department`
- Methods:
 - `get_details()` → `"[E001] Rahul | Engineering | ₹50000"`
 - `give_raise(amount)` → increases salary (only if amount > 0)
 - `calculate_bonus()` → returns 10% of salary

**Child class `Manager(Employee)`:**
- Extra attribute: `team_size`
- Override `calculate_bonus()` → returns 20% of salary
- New method: `approve_leave(emp_name)` → `"Priya approved leave for Rahul"`

**Child class `Intern(Employee)`:**
- Extra attribute: `mentor`
- Override `calculate_bonus()` → returns 5% of salary
- New method: `get_mentor()` → `"Amit's mentor is Priya"`

Then create a list of 5 employees (mix of Employee, Manager, Intern) and loop through them to print details and bonus for each.

**Expected output format:**
```
[E001] Rahul | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Priya | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Amit | Engineering | ₹20000 → Bonus: ₹1000.0
...
```

In [28]:
# Your code here
class Employee:
 def __init__(self, name, emp_id, salary, department):
  self.name = name
  self.emp_id = emp_id
  self.salary = salary
  self.department = department
 def get_details(self):
  return f"[{self.emp_id}] {self.name} | {self.department} | ₹{self.salary}"
 def give_raise(self, amount):
  if amount>0:
    self.salary+=amount
  else:
    print("Invalid raise amount!")
 def calculate_bonus(self,value=0.1):
  return value* self.salary

class Manager(Employee):
  def __init__(self, name, emp_id, salary, department, team_size):
    super().__init__(name, emp_id, salary, department)
    self.team_size = team_size
  def approve_leave(self, emp_name):
    return f"{self.name} approved leave for {emp_name}"
  def calculate_bonus(self,value=0.2):
   return super().calculate_bonus(value)

class Intern(Employee):
  def __init__(self, name, emp_id, salary, department, mentor):
    super().__init__(name, emp_id, salary, department)
    self.mentor = mentor
  def get_mentor(self):
    return f"{self.name}'s mentor is {self.mentor}"
  def calculate_bonus(self, value=0.05):
   return super().calculate_bonus(value)
emp1 = Employee("Bhu", "E001", 50000, "Engineering")
mgr1 = Manager("Sai",  "M001", 90000, "Engineering", 5)
int1 = Intern("Krishna", "I001", 20000, "Engineering", "Sai")
emp2 = Employee("Mahi", "E002", 60000, "HR")
int2 = Intern("Sushma", "I002", 25000, "Marketing", "Bhu")
employees = [emp1, mgr1, int1, emp2, int2]
for emp in employees:
    print(f"{emp.get_details()} → Bonus: ₹{emp.calculate_bonus()}")

[E001] Bhu | Engineering | ₹50000 → Bonus: ₹5000.0
[M001] Sai | Engineering | ₹90000 → Bonus: ₹18000.0
[I001] Krishna | Engineering | ₹20000 → Bonus: ₹1000.0
[E002] Mahi | HR | ₹60000 → Bonus: ₹6000.0
[I002] Sushma | Marketing | ₹25000 → Bonus: ₹1250.0


### Q11. `isinstance()` Check

Using the employees list from Q10, write a loop that:
1. Prints `"Manager alert!"` for any Manager objects
2. Prints the mentor name for any Intern objects
3. Just prints details for regular Employees

**Hint:** Use `isinstance(obj, ClassName)` to check the type.

In [29]:
# Your code here
for emp in employees:
    if isinstance(emp, Manager):
        print("Manager alert!")
    elif isinstance(emp, Intern):
        print(emp.get_mentor())
    else:
        print(emp.get_details())

[E001] Bhu | Engineering | ₹50000
Manager alert!
Krishna's mentor is Sai
[E002] Mahi | HR | ₹60000
Sushma's mentor is Bhu


### Q12. The `super()` Deep Dive

Look at this code:

```python
class Vehicle:
 def __init__(self, brand, year):
 self.brand = brand
 self.year = year
 print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
 super().__init__(brand, year)
 self.battery_kwh = battery_kwh
 print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
```

**Answer these:**
1. What will be printed when `tesla` is created? (predict first, then run)


2. What does `super().__init__(brand, year)` actually do?

3. What would happen if you remove the `super()` line? Try it — what attributes does `tesla` have now?

4. Why do we pass `brand` and `year` to `super().__init__()` but NOT `battery_kwh`?


In [36]:
# Test your predictions here
class Vehicle:
 def __init__(self, brand, year):
  self.brand = brand
  self.year = year
  print(f"Vehicle __init__ called for {brand}")

class ElectricCar(Vehicle):
 def __init__(self, brand, year, battery_kwh):
  super().__init__(brand, year)
  self.battery_kwh = battery_kwh
  print(f"ElectricCar __init__ called for {brand}")

tesla = ElectricCar("Tesla", 2024, 75)
print(tesla.battery_kwh)

Vehicle __init__ called for Tesla
ElectricCar __init__ called for Tesla
75


**Your answers:**

1. Printed output:
 Vehicle `__init__` called for Tesla

ElectricCar `__init__` called for Tesla

2. What super() does: Initialize the super class i.e, parent class Vehicle

3. Without super():
tesla only has battery_kwh

4. Why not pass battery_kwh: Because super class only accepts two parameters and battery_kwh is specific to ElectricCar

---

## Section 4: Challenge Problems

### Q13. Library System

Build a mini library:

**`Book` class:**
- Attributes: `title`, `author`, `is_available` (default True)

**`Library` class:**
- Attribute: `books` (an empty list to start)
- Methods:
 - `add_book(book)` → adds a Book object to the library
 - `show_available()` → prints only books where `is_available` is True
 - `lend_book(title)` → finds the book by title, sets `is_available = False`, prints confirmation. If not found or not available, print an error.
 - `return_book(title)` → finds the book, sets `is_available = True`
 - `search(keyword)` → returns all books where keyword is in the title OR author name (case-insensitive)

```python
lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
lib.search("python") # Should find Python Crash Course
```

In [43]:
# Your code here
class Book:
  def __init__(self,title,author,is_available=True):
    self.title = title
    self.author = author
    self.is_available = is_available
  def __str__(self):
    return f"{self.title} by {self.author}"


class Library:
  def __init__(self):
    self.books = []
  def add_book(self,book):
    self.books.append(book)
  def show_available(self):
    for book in self.books:
      if book.is_available:
        print(book.title)
  def lend_book(self,title):
    for book in self.books:
      if book.title==title:
        if book.is_available:
          book.is_available = False
          print(f"Book '{title}' has been lent.")
        else:
          print(f"Book '{title}' is not available.")
        return
    print(f"Book '{title}' not found.")
  def return_book(self,title):
    for book in self.books:
      if book.title==title:
        book.is_available=True
        print(f"Book '{title}' has been returned.")
        return
    print(f"Book '{title}' not found.")
  def search(self,keyword):
    results = []
    for book in self.books:
      if keyword.lower() in book.title.lower() or keyword.lower() in book.author.lower():
        results.append(book)
    return results

lib = Library()
lib.add_book(Book("Atomic Habits", "James Clear"))
lib.add_book(Book("Deep Work", "Cal Newport"))
lib.add_book(Book("Python Crash Course", "Eric Matthes"))

lib.show_available()
lib.lend_book("Deep Work")
lib.show_available() # Deep Work should NOT appear
lib.lend_book("Deep Work") # Should say "not available"
lib.return_book("Deep Work")
res=(lib.search("python")) # Should find Python Crash Course
for book in res:
  print(book)

Atomic Habits
Deep Work
Python Crash Course
Book 'Deep Work' has been lent.
Atomic Habits
Python Crash Course
Book 'Deep Work' is not available.
Book 'Deep Work' has been returned.
Python Crash Course by Eric Matthes


### Q14. School Report Card System

Build a system with:

**`Student` class:**
- Attributes: `name`, `roll_no`, `marks` (a dictionary like `{"math": 85, "science": 90, "english": 78}`)
- Methods:
 - `average()` → returns the average of all marks
 - `highest_subject()` → returns the subject with the highest mark
 - `pass_or_fail()` → returns `"Pass"` if average >= 40, else `"Fail"`
 - `__str__()` → nice formatted string

**`Topper(Student)` — inherits from Student:**
- Override `__str__()` to add a at the end
- New method: `motivational_quote()` → returns `"<name> says: Hard work pays off!"`

Create 3 students, find who has the highest average (the topper), and print everyone's report card.

**Expected output format:**
```
--- Report Card ---
Name: Rahul | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33 | Highest: science
Status: Pass

Name: Priya | Roll: 102
Marks: math=95, science=92, english=88
Average: 91.67 | Highest: math
Status: Pass
Priya says: Hard work pays off!
```

In [55]:
# Your code here
class Student:
  def __init__(self,name,roll_no,marks):
    self.name = name
    self.roll_no = roll_no
    self.marks = marks
  def average(self):
    return sum(self.marks.values())/len(self.marks)

  def highest_subject(self):
    return max(self.marks, key=self.marks.get)
  def pass_or_fail(self):
    if self.average()>=40:
      return "Pass"
    else:
      return "Fail"
  def __str__(self):
    marks_str = ', '.join([f"{subject}={mark}" for subject, mark in self.marks.items()])
    return f"\nName: {self.name} | Roll: {self.roll_no}\nMarks: {marks_str}\nAverage: {self.average()} | Highest: {self.highest_subject()}\nStatus: {self.pass_or_fail()}"
class Topper(Student):
  def __str__(self):
    return super().__str__() + "\n" + self.motivational_quote()
  def motivational_quote(self):
    return f"{self.name} says: Hard work pays off!"

s1 = Student("Bhu", 101, {"math": 85, "science": 90, "english": 78})
s2 = Student("Sai", 102, {"math": 95, "science": 92, "english": 88})
s3 = Student("Krishna", 103, {"math": 70, "science": 65, "english": 60})

students=[s1,s2,s3]
top_student = max(students, key=lambda s: s.average())
topper = Topper(top_student.name, top_student.roll_no, top_student.marks)
# print(topper)

print("--- Report Card ---")

for student in students:
  if student.roll_no == topper.roll_no:

    print(f"\nTopper details:{topper}")   # print Topper version (with quote)
  else:
    print(student)

--- Report Card ---

Name: Bhu | Roll: 101
Marks: math=85, science=90, english=78
Average: 84.33333333333333 | Highest: science
Status: Pass

Topper details:
Name: Sai | Roll: 102
Marks: math=95, science=92, english=88
Average: 91.66666666666667 | Highest: math
Status: Pass
Sai says: Hard work pays off!

Name: Krishna | Roll: 103
Marks: math=70, science=65, english=60
Average: 65.0 | Highest: math
Status: Pass


## Section 5: Conceptual Questions

Answer these in your own words — no code needed, just understanding.

### Q15. Short Answers

**Write your answers below each question:**

**a) What is the difference between a class and an object?**

*Your answer:Class is just a blue print and object is an instance of class*

**b) Why do we need `self` in every method? What would happen without it?**

*Your answer:There will be so many objects of class, each  having its own attribute values.To modify specific objects values we use self,which refers to the current object's values and methods*

**c) What is the difference between `__init__` and a regular method?**

*Your answer:`__init__` is a dunder method immediately called when obj created, it is to initialize object's attributes. while regular method has simple naming convention and called on purpose*

**d) Can a child class have attributes that the parent class doesn't? Give an example from the Employee system.**

*Your answer:Yes,Employee has attributes name,emp_id,salary,department. Manager has attributes of Employee and also team_size as extra attribute*

**e) What is method overriding? Why is it useful?**

*Your answer:During inheritance all the methods of parent class are inherited into child class but if we want to change behaviour of a method we use same method name anad change behaviour*

**f) If you run `dir(5)`, you see `__add__`, `__sub__`, `__mul__` etc. What does this tell you about how Python handles arithmetic?**

*Your answer:Yes,these tell us `+`,`-`,`*` are treated as method calls `__add__`, `__sub__`, `__mul__`

---

## Section 6: Git & GitHub

Now that you've written real code, let's learn how to save and share it properly.

### Q16. Git Basics — Theory

**Answer these:**

**a) What is the difference between Git and GitHub?**

*Your answer:Git is a version ctl system locally, Github is a cloud platform to store and share git repos*

**b) What do each of these commands do? Write one-line explanations:**

| Command | What it does |
|---------|-------------|
| `git init` | git tracks our work now|
| `git add .` | add all files to staging|
| `git commit -m "message"` | save our changes with a message|
| `git status` |status of files A,U,M |
| `git log` | commit history|
| `git push` | push our work to github|
| `git pull` | update our local code from remote |
| `git clone <url>` |copy remote repo to local system |

**c) What is a `.gitignore` file? Why would you add `__pycache__/` or `.env` to it?**

*Your answer:Just tell git to not track these files.`__pycache__/ stores compiles python files .pyc which are not needed to tracked. .env contains sensitive data like passwords,keys etc .so we dont want it show on github*

**d) What is the difference between `git add .` and `git add filename.py`?**

*Your answer: git add . adds all files to staging area . git add filename.py add only one file .*

### Q17. Git Workflow — Practical Task

Do the following steps and **paste screenshots or the terminal output** in the markdown cell below:

1. Create a new folder called `oops-assignment`
2. Run `git init` inside it
3. Create a file `employee.py` with your Employee class from Q10
4. Run `git status` — what does it show?
5. Run `git add employee.py`
6. Run `git status` again — what changed?
7. Run `git commit -m "Add Employee class with inheritance"`
8. Run `git log` — paste the output

**Bonus:** Create a GitHub repository, push your code, and paste the repository link here.

**Paste your terminal outputs / screenshots here:**

```
# git status (before add):
user@user-TravelMate-P214-53:~/Desktop/oops-assignment$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	employee.py

nothing added to commit but untracked files present (use "git add" to track)
```
```
# git status (after add):
user@user-TravelMate-P214-53:~/Desktop/oops-assignment$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   employee.py
```
```
# git log:
user@user-TravelMate-P214-53:~/Desktop/oops-assignment$ git log
commit 4c1b523d69d73d7b215992e8251bbcdece4d62a1 (HEAD -> master)
Author: Bhuvaneshwari-bhu <bhuvaneshwariryakala@gmail.com>
Date:   Sun Mar 22 01:23:25 2026 +0530

    Add Employee class with inheritance
```
```
# GitHub repo link (bonus):https://github.com/Bhuvaneshwari-bhu/oops-assignment


git remote add origin git@github.com:Bhuvaneshwari-bhu/oops-assignment.git
(base) user@user-TravelMate-P214-53:~/Desktop/oops-assignment$ git branch -M main
git push -u origin main
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 819 bytes | 819.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To github.com:Bhuvaneshwari-bhu/oops-assignment.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.

```

---

### Q18. Git Scenario Questions

**a)** You accidentally committed a file with your password in it. The commit is already done but NOT pushed yet. How do you undo it?

*Your answer: `git reset --soft HEAD~1` this will remove last commit and keep file in staging area. now i will remove password frome file and commit*

**b)** You and your teammate both edited the same file. When you `git pull`, you get a "merge conflict." In simple terms, what happened and what should you do?

*Your answer:both of us changed the same part of file.open file and look for markers , manually choose one and combine and commit correct version*

**c)** What is the difference between `git pull` and `git fetch`?

*Your answer:git fetch downloads changes but not merge.git pull download and merge into current branch*

**d)** Why should you write meaningful commit messages instead of `"fixed stuff"` or `"update"`?

*Your answer: It has to be understood by others who merge them and even if we look after some days one has to clearly understand what was changed.*

---

## Section 7: Reflection

### Q19. Connect the Dots

**a)** Before this class, how did you think Python's `+` operator worked? How do you think about it now?

*Your answer:I hve no idea about it before . Got full clarity now*

**b)** You used `.upper()`, `.append()`, `.sort()` many times before. Did you ever think about WHERE these methods come from? What did the Cmd+Click demo in VS Code change for you?

*Your answer:I thought those were some predefined and not focused much on their existence just byhearted. Now feel like i can also create some methods like that.*

**c)** In your own words, explain to a non-coder friend: why do we need classes? Use the employee example.

*Your answer:Classes are used to create our own datastructures when built-in ones like list/dictionaries are not enough.For example, in an employee system we can create a class emp to store details like name,sal,dep together and alos define some actions like give hike.This helps organize data and behaviour at once place and reusable manner . It is easy to access, no confusion. *

---

## Submission Instructions

1. Complete all sections in this notebook
2. **Restart Kernel & Run All** to make sure everything works
3. Save the notebook
4. Push to your GitHub repository with the commit message: `"Complete OOP & Inheritance Assignment"`
5. Share the GitHub repository link

> **Deadline:** *[To be announced by trainer]*

---

> *"Python's creators built `str` with `.upper()` and `list` with `.append()`. Today you built `Employee` with `.give_raise()`. You're a class designer now."*